### PR TITLE
X10/X12S: Int/Ext Antenna UI

### LINKED ISSUE #1567: Missing Antenna Parameter in Horus X10s
**Describe the bug**
There is no possibilty to change the antenna in the X10s.
Missing in X10s Radio Setting/Hardware and Model Setup.
In Companion this parameter is adjustable.

**To Reproduce**
screenshots from OTX 2.3.14

**Expected behavior**
adjustable antenna parameter in X10s

**Screenshots**
Companion EdgeTX:
grafik
grafik

EdgeTX 2.6.0
grafik
grafik

OTX 2.3.14
grafik
grafik

**General information**
 - EdgeTX version (2.6.0 x10-338d4d2)
 - Hardware (Frsky Horus X10s)

### PR DESCRIPTION
**Pull request by pfeerick**
Fixes #1567

Summary of changes:
- implements UI for internal/external antenna selection

And for prosperity/full transparency, I started this, but Raphael finished it ... you just can't see he finished re-writing the remainder of it due to the rebase. ;)

USE AT YOUR OWN RISK **until properly tested**! (aka have both antenna fitted until this warning removed).

### CODE REVIEW

**Comment by pfeerick** [comment]
Rebased to adjust for LVGL. However I haven't implemented `colorlcd/hw_intmodule.cpp` quite right as it doesn't show crossfire or antenna options when applicable. Entirely my own fault as still haven't looked at how things are done in hybrid LVGL/libopenui land.

File: radio/src/gui/colorlcd/module_setup.cpp [hunk 1]
```diff
@@ -288,6 +288,34 @@ void ModuleWindow::updateModule()
...
+#if defined(INTERNAL_MODULE_PXX1) && defined(EXTERNAL_ANTENNA)
+  if (moduleIdx == INTERNAL_MODULE && isModuleXJT(moduleIdx) &&
+      g_eeGeneral.antennaMode == ANTENNA_MODE_PER_MODEL) {
+    auto line = newLine(&grid);
+    new StaticText(line, rect_t{}, STR_ANTENNA, 0, COLOR_THEME_PRIMARY1);
+    auto antennaChoice = new Choice(
+        line, rect_t{}, STR_ANTENNA_MODES, ANTENNA_MODE_INTERNAL,
+        ANTENNA_MODE_EXTERNAL,
+        GET_DEFAULT(g_model.moduleData[INTERNAL_MODULE].pxx.antennaMode),
+        [=](int32_t antenna) -> void {
```
Comment (raphaelcoeffic) [inline radio/src/gui/colorlcd/module_setup.cpp:300]: For code readability, you probably want to have this `Choice` be a specific component which has this code as a method of its own class (inherited from `Choice`).

File: radio/src/storage/storage_common.cpp [hunk 2]
```diff
@@ -132,33 +130,52 @@ void checkExternalAntenna()
 {
   if (isModuleXJT(INTERNAL_MODULE)) {
     if (g_eeGeneral.antennaMode == ANTENNA_MODE_EXTERNAL) {
+      // TRACE("checkExternalAntenna(): External");
       globalData.externalAntennaEnabled = true;
-    }
-    else if (g_eeGeneral.antennaMode == ANTENNA_MODE_PER_MODEL && g_model.moduleData[INTERNAL_MODULE].pxx.antennaMode == ANTENNA_MODE_EXTERNAL) {
+    } else if (g_eeGeneral.antennaMode == ANTENNA_MODE_PER_MODEL &&
```
Comment (raphaelcoeffic) [inline radio/src/storage/storage_common.cpp:135]: I'd like to suggest moving this code to PXX1 specific implementation file, so that it does not clutter the generic parts in `storage_common.cpp`.

File: radio/src/gui/colorlcd/hw_intmodule.cpp [hunk 3]
```diff
@@ -50,12 +50,44 @@ InternalModuleWindow::InternalModuleWindow(Window *parent) :
...
 
+  ant_box = box->getLvObj();
+  lv_obj_set_width(ant_box, LV_SIZE_CONTENT);
+  lv_obj_set_style_flex_cross_place(ant_box, LV_FLEX_ALIGN_CENTER, 0);
+
+  new StaticText(box, rect_t{}, STR_ANTENNA, 0, COLOR_THEME_PRIMARY1);
+  new Choice(
+      box, rect_t{}, STR_ANTENNA_MODES, ANTENNA_MODE_INTERNAL,
+      ANTENNA_MODE_EXTERNAL, GET_DEFAULT(g_eeGeneral.antennaMode),
+      [](int antenna) {
```
Comment (raphaelcoeffic) [inline radio/src/gui/colorlcd/hw_intmodule.cpp:65]: This code could be common with the model specific code to avoid copying it.
