### PR TITLE
Reset logical switch v2 range if v1 changes

### LINKED ISSUE #375: Calculated Sensor Special function a<x max value 100mah
I can create a calculated sensor for Consumption using Curr telemetry but if I create a special function to trigger an alert from that sensor the maximum value available is 100mah

Steps to reproduce the behaviour:
1) Add Telemetry sensors (in my case from betaflight)
2) Create a calculated sensor with Curr as the source and consumption as the type
3) Create a Logical switch a<x with a mah value greater than 100mah (I use 1000mah as a low battery alarm trigger)

**Expected behavior**
In OtX any value can be assigned

**General information**
 - EdgeTX version (e.g. 2.4.0 latest
 - Hardware Jumper T18

### PR DESCRIPTION
**Pull request by pfeerick**
Resolves #375 

Use the v1 handler to update v2 range if the v2 source box has already
been created, so that the min/max values are correctly updated from v1.

Read it and weep over my atrocious code. :-P

As always, open to suggestions and being told there's a better way to do it. TX16S hasn't crashed yet :-P

### CODE REVIEW

**Comment by pfeerick** [comment]
Do you think this should also re-set the v2 value? I'm in two minds, as there is an edge case where if you choose a v1 value that allows negative values, and then change v1 to one that doesn't (i.e. `Batt` is 0 - 255, `GV9` is -1024 - 1024) ... the v2 value is left as it is (which is out of range)... but as soon as you scroll it will jump back into range. If I were to to simply reset it, it does mean values that are in range would be cleared... which could be annoying...

File: radio/src/gui/colorlcd/model_logical_switches.cpp [hunk 1]
```diff
@@ -162,6 +162,13 @@ class LogicalSwitchEditPage: public Page
                            cs->v1 = newValue;
                            SET_DIRTY();
                            v2Edit->invalidate();
```
Comment (raphaelcoeffic) [inline radio/src/gui/colorlcd/model_logical_switches.cpp:164]: I believe this line should be inside the `if` block, at the end of it. It triggers a re-draw of the UI component. Functionally, it does not make a difference (whereby, it makes sense to check it for `nullptr` value before dereferencing), but logically, it is cleaner.

**Comment by raphaelcoeffic** [comment]
> Do you think this should also re-set the v2 value? I'm in two minds, as there is an edge case where if you choose a v1 value that allows negative values, and then change v1 to one that doesn't (i.e. `Batt` is 0 - 255, `GV9` is -1024 - 1024) ... the v2 value is left as it is (which is out of range)... but as soon as you scroll it will jump back into range. If I were to to simply reset it, it does mean values that are in range would be cleared... which could be annoying...

Makes sense to me, that's right.

File: radio/src/gui/colorlcd/model_logical_switches.cpp (hunk 1 above)
Comment (pfeerick) [reply radio/src/gui/colorlcd/model_logical_switches.cpp]: Ah, yes... that makes sense... I was sort of wondering why it could get away with that as everything I added was protected within the nullptr check ;). Moved.

**Comment by pfeerick** [comment]
I've removed the range check in favour of fixing the issue properly as it's also present in B&W transmitters... so will be addressed per  #393 instead.
