### PR TITLE
fix(dsmp): binding issue, channel update rate, unexpected servo movement on startup - 2.11

### LINKED ISSUE #5614: LemonDSMP: No telemetry, and CH8 not working
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

When using the LemonDSMP Module, there is no telemetry from the [LM0086 7CH](https://lemon-rx.com/index.php?route=product/product&path=76&product_id=270) receiver, and it appears that CH8 (and maybe also CH7 as stabilsation should still do something with minimum gain) is not working / locked to  -150. I've encountered this myself, and it has been reported by another on RCG
- https://www.rcgroups.com/forums/showpost.php?p=53053491&postcount=8386
- https://www.rcgroups.com/forums/showpost.php?p=53053971&postcount=8390

### Expected Behavior

For Telemetry to work, and for all available channels to work correctly. 

### Steps To Reproduce

1. Bind LM0086 RX to LemonRX DSMP module with LemonRX DSMP set as the module protocol
2. Attempt telemetry scan - nothing will be found
3. Try to use CH7/8 for stabilisation control/gain - nothing will happen

### Version

2.10.4

### Transmitter

RadioMaster TX16S / TX16SMK2

### Operating System (OS)

_No response_

### OS Version

_No response_

### Anything else?

I encountered this when originally testing 2.10 prior to the first RC, and was able to repo it also in 2.7.1. However, at the same time, I have working telemetry with the LemonRX DSMP module if using a Spektrum AR637T receiver, and if I use the MPM I can get telemetry from the LM0086 receiver. 

Note: this is the first gen LM0086, **not** the second generation LM0086X if that has any bearing on this.

### PR DESCRIPTION
**Pull request by frankiearzu**
NOTE:  For Branch 2.11

Fixes  #5614

TESTING: TX16S and Boxer

Summary of changes:
1. Fixes sending channels from 11ms to 22ms intervals. The DSMP module is designed for 22ms.. This was causing to loss a lot of messages being sent.
Image

This s the offending line:
Image

3. Fix Binding Problem. The module was getting crazy after bind.. the TX needed to be restarted to correct.. This was caused by trying to restart the module in two different places at the same time.

4. Fix unexpected servo movement during startup. If you have the RX power ON before the radio, or the radio is powered cycle, or switching models.. Sometimes the servos will move for a bit to unexpected positions. This is caused that the Setup package was not received before sending channels.. solution, send setup multiple times instead of once!  **Really dangerous situation with electric motors starting unexpectedly, even for a bit**. NOTE: Not 100% solved, but it eliminates the problem 80% of the time. The only way to really solve it is in the Module firmware.

6. Show on the module screen the Status of the module (Version + Protocol).

7. Added channel order mapping: AETR->TAER on the module screen. This change added a new YAML attribute and translation.

8. Move DSMP code into a separate file from DSM2 (pulses folder).

9. Spektrum forward programming capabilities (for v2 firmware).

10. In Spectrum.cpp, when receiving the bind packet, there was conditional code for handling MultiModule and DSMP specifics.   move the module-specific code to the respective multi.cpp and dsmp.cpp. This is mostly to turn off binding on the module screen and change from DSM AUTO to the protocol negotiated. The Spektrum.cpp keeps only the common part for both.

11.  ### TELEMETRY:  DSMP + some old LemonRX Gen2 still does not receive telemetry.. works with newer LemonRX Gen2. The strange part is that the same same receiver telemetry works well with the Multi-Module.  Still a mistery what could be going on. DSMP+Spektrum AR637T telemetry works.

GUI changes for both Color and both versions of B&W.

image
image

### CODE REVIEW

**Comment by frankiearzu** [comment]
Looking into the problem with T8

**Comment by frankiearzu** [comment]
Working in adding the extra module flag to Companion

**Comment by frankiearzu** [comment]
Video explaining the problems and fixes:
https://1drv.ms/v/c/d7d173dc4753590f/ERxN2KCud9NLrQBmzKw8iNkBFHTAZajPb49f5xtvww2gCA?e=u8u0CQ

File: radio/src/pulses/modules_helpers.h [hunk 1]
```diff
@@ -487,7 +487,7 @@ inline int8_t minModuleChannels(uint8_t idx)
   else if (isModuleSBUS(idx))
     return 16;
   else if (isModuleDSMP(idx))
-    return maxModuleChannels(idx);
+    return 1;
```
Comment (pfeerick) [inline radio/src/pulses/modules_helpers.h]: "module assume always start with Ch1." 

Was this just lost in translation? As this shouldn't in relation to the starting channel, but the *minimum* number of channels, i.e. so you can't bring the change range fields any closer than this value (or any bigger than maxModuleChannels).
