### PR TITLE
fix(radio): prevent starting another USART send when one is already in progress

### LINKED ISSUE #3054: Wireless trainer connection using internal MPM intermitent when external ELRS module is turned on
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

I want to use a FlySky fs-i6x transmitter as a Student connected to my Radiomaster TX16S on the internal MPM using the FlySky AFHDS 2A RX protocol. The TX16S is connected to the model with an external ELRS module.

Here are the steps I did:
1) Turn OFF the External module
2) Set the Trainer mode (button to activate Trainer mode on Special Functions and Trainer mode to Master/Multi)
3) Bind the FS-i6x radio to my TX16s

At this stage, the Trainer model works fine. I can confirm on the Channel Monitor that I have control if the Trainer button is disabled, and the FS-i6x has control if the Trainer button is enabled.

The strange behavior happens when I turn on the external ELRS module. As soon it is turned on, the Student/Trainer connection becomes intermittent, jumping from connected to Trainer connection lost every second. 

I am posting a video of the behavior for a better understanding.

https://user-images.githubusercontent.com/18128610/212780579-65ea1cc2-d674-443a-9ebb-840ab4c9624e.mp4

### Expected Behavior

The connection between the fs-i6x and the TX16S should continue to be stable even when the external module is ON.

### Steps To Reproduce

1) Turn OFF the External module
2) Set the Trainer mode (button to activate Trainer mode on Special Functions and Trainer mode to Master/Multi)
3) Bind the FS-i6x radio to my TX16s
4) Confirm Student/Trainer behaviour works as expected on Channel Monitor
5) Turn on the external module on CRSF (ExpressLRS)
6) Strange behavior happens - Connection between Student and Master radio becomes intermittent.

### Version

2.8.0

### Transmitter

Radiomaster TX16S / TX16SMK2

### Anything else?

_No response_

### LINKED ISSUE #6609: TX15: possible conflict between internal and external modles
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

When both internal and external multi are used, some configurations lead to 'no telemetry' state on external module

### Expected Behavior

Both can work independantly

### Steps To Reproduce

1. set internal ELRS to ON, with frame rate above 250Hz
2. set external module to MULTI
3. turn off radio
4. turn on radio
5. go to external module setttings: module reports no telemetry 

### Version

Nightly (Please give date/commit below)

### Transmitter

RadioMaster TX15

### Operating System (OS)

_No response_

### OS Version

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by 3djc**
When 2 module are in use, the internal drives mixer scheduling. In case of ELRS, this could drive mixer runs as low as 1ms

Issue #6609 happens because a MPM frame takes about 3ms to be sent. In current code send is restarted before the frame is even finished when internal elrs rate is set above 250hz, resulting in a continuous flow of meaningless bytes

Before
image

After
image

This prevent serial sent to be done if one is still in progress, which makes sense for any serial transmission 

This fixes #6609, fixes #3054

### CODE REVIEW

File: radio/src/targets/common/arm/stm32/stm32_usart_driver.cpp [hunk 1]
```diff
@@ -558,6 +558,12 @@ void stm32_usart_send_byte(const stm32_usart_t* usart, uint8_t byte)
 
 void stm32_usart_send_buffer(const stm32_usart_t* usart, const uint8_t * data, uint32_t size)
 {
+
+  if (!stm32_usart_tx_completed(usart)) {
+    // Transmission is already in progress, abort
+    return;
```
Comment (raphaelcoeffic) [inline radio/src/targets/common/arm/stm32/stm32_usart_driver.cpp:564]: We might want to introduce return codes to be able to propagate errors. Dropping the packet here is however all we can do, except if blocking is wished, in which case we could block.

Comment (3djc) [reply radio/src/targets/common/arm/stm32/stm32_usart_driver.cpp:564]: I did consider returns code, but most, if not all of the similar drivers don't handle return codes. It could be done, but as part of a bigger driver refresh (including ability to read error counter for examples)

**Comment by pfeerick** [comment]
Long standing issue (discovered/reported in 2.7) #3054 is also resolved by this PR ;) 🚀 Was otherwise still present in both 2.11 and latest nightly.
