### PR TITLE
Fix the BUG of V0 receiver setting IBUS SBUS; add the setting item of…

### LINKED ISSUE #3388: BUG of EL18 internal RF： i-BUS, iBUS2 display error
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

1、i-BUS, iBUS2 information display error,
2、Select i-BUS2 BIND failed
image

### Expected Behavior

Displayed : i-BUS out, i-BUS in
Choose not to affect BIND

### Steps To Reproduce

internal RF -> Module options-> External bus type selection.

### Version

2.8.0

### Transmitter

Flysky EL18

### Anything else?

No response

### LINKED ISSUE #3389: BUG of EL18 internal RF：BIND with FTr4/FGr4s/FGr4P fails to set S.BUS
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

BIND with FTr4/FGr4s/FGr4P fails to set S.BUS

### Expected Behavior

BIND with FTr4/FGr4s/FGr4P Set S.BUS successfully

### Steps To Reproduce

1、internal RF -> Module options-> BIND
2、Check RX signal no S.BUS

### Version

2.8.0

### Transmitter

Flysky EL18

### Anything else?

No response

### LINKED ISSUE #3390: BUG of EL18 internal RF：BIND with FTr8 cannot set the PWM frequency of each channel
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

BIND with FTr8 cannot set the PWM frequency of each channel
Only set all channels to the same PWM frequency
image

### Expected Behavior

Each channel PWM frequency can be set

### Steps To Reproduce

internal RF -> Module options-> PWM freqyency

### Version

2.8.0

### Transmitter

Flysky EL18

### Anything else?

No response

### PR DESCRIPTION
**Pull request by Xy2019**
… INRM301.

Fixes #3388
Fixes #3389
Fixes #3390

Summary of changes:
1.Added V1 receiver's setting of PWM and synchronization for each channel; added restrictions on setting NewPort (four NewPorts only support one interface output PPM at the same time. SBUS IBUS-IN IBUS-OUT is the same).
2.Modify the BUG of FTr4/FGr4s/FGr4P three receiving settings IBUS-IN IBUS-OUT SBUS. After the binding is successful, get the product number of the receiver, and then resend the command to set IBUS SBUS according to the product number. For example, if the user selects SBUS and the binding is successful, the program must send IBUS IBUS-OUT SBUS commands in sequence.

### CODE REVIEW

File: radio/src/pulses/afhds3.cpp [hunk 1]
```diff
@@ -145,15 +176,29 @@ enum DeviceAddress {
...
+PACK(struct ModuleVersion
+{
+  uint16_t company_number;
+  uint32_t tx_id;
+  uint32_t rx_id;
+  uint32_t product_number;
+  uint32_t hardwere_version;
+  uint32_t bootloader_version;
+  uint32_t firmware_version;
+  uint32_t rf_version;
```
Comment (pfeerick) [inline radio/src/pulses/afhds3.cpp:188]: Either change this back to camel case, or update ln 615-615 with the new names. hardwere_version has a typo btw.
