### PR TITLE
fix(sim): libsims not unloading

### LINKED ISSUE #5919: Radio settings changed in simulator persist temporarily when they should be reset.
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Simulator

### Current Behavior

After setting a custom name on an Axis, Pot or Switch in the simulator the custom name persists after closing and re-opening the simulator.
The custom name is not shown in the companion radio settings, and does not survive closing and re-opening companion.

### Expected Behavior

All fields should be reset on closing the simulator window.

### Steps To Reproduce

- Start companion, create a new blank ETX file (no models)
- Start simulator, a default model is created
- Set a custom name for an axis, pot or switch in the radio hardware page
- Close the simulator
- Run the simulator again - check the axis/pot/switch settings. The names persist.

### Version

2.11.0-rc

### Transmitter

RadioMaster TX16S / TX16SMK2

### Operating System (OS)

_No response_

### OS Version

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by elecpower**
Fixes #5919
Alternative solution to #5931

Summary of changes:
- Companion writes models and settings to a temporary directory and launches the standalone Simulator in a new process
- the Simulator startup dialog is bypassed unless something goes unexpectantly wrong
- Companion waits for the Simulator to finish before becoming responsive (like a modal dialog)
- new Simulator cli option flags to permit Companion to pass flags that it previously passed to its self contained simulator

### CODE REVIEW

File: companion/src/helpers.cpp [hunk 1]
```diff
@@ -369,35 +370,70 @@ void startSimulation(QWidget * parent, RadioData & radioData, int modelIdx)
...
+  Storage storage(tmpDir.path());
+  if (!storage.write(*simuData)) {
+    QString resultMsg = QCoreApplication::translate("Companion", "Error writing models and settings to temporary directory.");
+    QMessageBox::critical(NULL, QCoreApplication::translate("Companion", "Simulator Error"), resultMsg);
+    return;
+  }
+
+  const QString path = QCoreApplication::applicationDirPath();
+
+  #if Q_OS_WIN
```
Comment (rotorman) [inline companion/src/helpers.cpp:394]: Might need `#include <QtGlobal>` for Qt 5.15 https://doc.qt.io/qt-5/qtglobal.html and `#include <QtSystemDetection>`  according to https://doc.qt.io/qt-6/qtsystemdetection.html#Q_OS_WIN for Qt 6.8

Comment (elecpower) [reply companion/src/helpers.cpp:395]: 2 out of 3 compile just gotta love consistency

Comment (elecpower) [reply companion/src/helpers.cpp:395]: Added include so let's see if success

Comment (rotorman) [reply companion/src/helpers.cpp:395]: Can you try `#if defined (Q_OS_WIN)` instead?

**Comment by pfeerick** [comment]
Ouch... both Windows and Linux Mint did *not* like this...  Simulator would not start for either through Companion. Windows standalone worked fine, and did Linux (I cheated and used the path in the debug log to start it on Linux/Mint while Companion was running). Debug logs and screenshots in the attached zips. I didn't have a 2.11 on that Windows machine so couldn't give an a/b log for that. 
[2.11-rc2-mint.zip](https://github.com/user-attachments/files/19528055/2.11-rc2-mint.zip)
[6005-mint.zip](https://github.com/user-attachments/files/19528056/6005-mint.zip)
[6005-win.zip](https://github.com/user-attachments/files/19528057/6005-win.zip)

**Comment by pfeerick** [comment]
Hm, this makes no sense at all... I just woke up the laptop, ran the 6005 AppImage again, and this time Simulator through Companion worked... !?

**Comment by elecpower** [comment]
Would appear the --flags parameter is being passed as unicode instead of an integer. 
Windows - if you start the simulator on the model file you get the usage message but if you start from model edit it finishes with an error. In either case the flag is not considered valid. I think the \u0000 is null so that would explain why message no flags value.
Ubuntu - I ran all my tests okay on Ubuntu so can only assume the OSes handle the unicode value differently.
I will fix.

**Comment by elecpower** [comment]
Tested Windows 10 exes TX16S and X9D+ both current model and radio with Play Sound and Play Track SFs. Sounds play in Companion Model Edit and simulated radio.
Tested Ubuntu 22.04 AppImage same radios and settings. Sounds DO NOT play in Companion Model Edit but do in simulated radio.

**Review by pfeerick — APPROVED** [review]
That would probably be #1435 still lurking. 😭 

And lol... we're obviously testing at the same time... I was about to post that I've now tried this on two Windows 11 installs and two Linux Mint installs, and "Simulate Radio", "Simulate model" and "Simulate" while editing model all seem to be working perfectly now... multiple radio profiles, with and without SD structure paths. I have the same issue still previewing sounds in the "Edit Model" SF tab, but other than that everything seems to be working perfectly again now :)

**Comment by philmoz** [comment]
This does not work on MacOS.
Downloaded and ran build from this PR - when trying to start simulator get this error:
Screenshot 2025-04-01 at 4 50 29 PM

**Comment by elecpower** [comment]
Your logs might be helpful. For starters the Companion log includes the command line used to start the simulator.
Its likely I guessed it wrong for MacOS or needs a wrapper or ...

**Comment by philmoz** [comment]
MacOS Companion build has never included the stand alone simulator app so trying to use it to run the simulator was never going to work.

Even manually building simulator and copying the executable to the MacOS folder in the app bundle fails because it is trying to run 'simulator30' not 'simulator'.

**Comment by elecpower** [comment]
> MacOS Companion build has never included the stand alone simulator app so trying to use it to run the simulator was never going to work.

No one gave me the heads up.

> Even manually building simulator and copying the executable to the MacOS folder in the app bundle fails because it is trying to run 'simulator30' not 'simulator'.

Well that is at least fixable subject to bundling

**Comment by elecpower** [comment]
> After building simulator, renaming it to simulator30 and copying it to the Companion bundle it will run. But the experience on MacOS is not nice - the main app blocks completely while the simulator is running and because it is a separate app the main app show the spinning wheel icon whenever the mouse hovers over it and Finder shows the app as 'not responding'.

Same on other OSes to "replicate" simulator modal dialog

**Comment by philmoz** [comment]
Key buttons have gone funky with this PR on MacOS:

https://github.com/user-attachments/assets/fe853506-a856-49b1-a45d-feecfdbfbf29

**Comment by elecpower** [comment]
> Key buttons have gone funky with this PR on MacOS

Rechecked Win and AppImage and they are okay. Another MacOS anomaly. The change did not go near the simulator ui.

**Comment by elecpower** [comment]
> Same on other OSes to "replicate" simulator modal dialog

Could launch the simulator independent but then the user could launch multiple instances though I could prevent that and display a message though will need to test detection across all oses.

However only allowing one instance would impact those users who might be launching multiple standalone copies now say for different radio profiles or Companion simulator and stand alone Simulator.

**Comment by elecpower** [comment]
@philmoz when you build the MacOS install target does the simulator app get copied to the same directory as companion app and not end up in the dmg or its not even copied?

**Comment by philmoz** [comment]
The simulator.app is not built or included in the MacOS install package. Never has been.
It can only be built manually.

**Comment by philmoz** [comment]
> > Key buttons have gone funky with this PR on MacOS
> 
> Rechecked Win and AppImage and they are okay. Another MacOS anomaly. The change did not go near the simulator ui.

Difference between running the simulator from the libraries in companion and running in the stand alone simulator app.
The stand alone simulator has this problem with the buttons (even in older versions).

**Comment by philmoz** [comment]
I found the culprit that is stopping the libraries from unloaded - it is one of the updates to the STB image library.

Don't know which change in STB is the root cause yet; but rolling back to the version used in 2.10 fixes the problem.

**Comment by philmoz** [comment]
I have create a PR (6059) that fixes the library unload issue and reverts the changes from this PR - so Companion will run the simulator directly from the libraries.

This removes the breaking changes to Companion on MacOS.

**Comment by philmoz** [comment]
Another issue with this is that the two programs have separate storage for the app settings.
For example changing the SD path in companion does not flow through to the simulator program.
