### PR TITLE
Companion trainer modes OFF and Master-Multi available for all radios

### LINKED ISSUE #1796: Companion - can not set Trainer Mode to OFF and Master/Multi
**Describe the bug**
Trainer mode cannot be set to Master/Multi in the Companion, but it works on the transmitter.

**To Reproduce**
using latest EdgeTX on Zorro and latest Companion

**Screenshots**

Screenshot 2022-04-03 095542

**General information**
 - EdgeTX 2.7 https://github.com/EdgeTX/edgetx/commit/092acd2d96955e2551292185631c3de391830206
 - Companion 2.7 https://github.com/EdgeTX/edgetx/commit/1cda6e6ddd20078dba39e9d5b1f9a559b526f881
 - Zorro

### PR DESCRIPTION
**Pull request by elecpower**
Fixes #1796

Summary of changes:
- update trainer modes list item availability
- standardise trainer mode Off to OFF

### CODE REVIEW

File: radio/src/translations/de.h.txt [hunk 1]
```diff
@@ -325,7 +325,7 @@
 #define TR_VTMRMODES          			 "AUS""EIN""GSs""GS%""GSt"
 
 #define LEN_VTRAINERMODES              "\022"
-#define TR_VTRAINER_MASTER_OFF         "Off\0              "
+#define TR_VTRAINER_MASTER_OFF         "OFF\0              "
```
Comment (TheIsotopes) [inline radio/src/translations/de.h.txt:328]: Please use `AUS` instead of `OFF`.

It would be nice if you could change `Master` to `Lehrer` and `Slave` to` Schüler` just a little further down (Bluetooth / Multi).

**Review by TheIsotopes — CHANGES_REQUESTED** [review]

File: radio/src/translations/de.h.txt (hunk 1 above)
Comment (pfeerick) [reply radio/src/translations/de.h.txt:328]: I'll do those now as I'm about to review this before merge...

File: radio/src/translations/de.h.txt [hunk 2]
```diff
@@ -325,14 +325,14 @@
...
+#define TR_VTRAINER_MASTER_OFF         "AUS\0              "
 #define TR_VTRAINER_MASTER_JACK        "Lehrer/Buchse\0    "
 #define TR_VTRAINER_SLAVE_JACK         "Schüler/Buchse\0   "
 #define TR_VTRAINER_MASTER_SBUS_MODULE "Lehrer/SBUS Modul\0"
 #define TR_VTRAINER_MASTER_CPPM_MODULE "Lehrer/CPPM Modul\0"
 #define TR_VTRAINER_MASTER_BATTERY     "Lehrer/Serial\0    "
-#define TR_VTRAINER_BLUETOOTH          TR("Master/BT\0        ""Slave/BT\0         ", "Master/Bluetooth\0 ""Slave/Bluetooth\0  ")
-#define TR_VTRAINER_MULTI              "Master/Multi"
+#define TR_VTRAINER_BLUETOOTH          TR("Lehrer/BT\0        ""Schüler/BT\0       ", "Lehrer/Bluetooth\0 ""Schüler/Bluetooth\0")
+#define TR_VTRAINER_MULTI              "Lehrer/Multi"
```
Comment (TheIsotopes) [inline radio/src/translations/de.h.txt:335]: looks good now

File: radio/src/translations/de.h.txt (hunk 1 above)
Comment (TheIsotopes) [reply radio/src/translations/de.h.txt]: @pfeerick thx

**Comment by TheIsotopes** [comment]
@pfeerick Can not find commit https://github.com/EdgeTX/edgetx/pull/1806/commits/82c61817fb725ac65bfce4e9af5577886e6a815c in 2.7 Branch the over two commits from this PR are merged?!

**Comment by pfeerick** [comment]
I was trying Fork for the cherry-picking for the first time, and ended up merging the commits separately rather than the squash merge... so it is in 2.7 ;)

https://github.com/EdgeTX/edgetx/commit/0305ac7a012abbd410789eaeec936c8d146ed0af
https://github.com/EdgeTX/edgetx/commit/6a22b0a9a75fe1562774c0b162ae07ed7773ad27

**Comment by pfeerick** [comment]
Dammit... no, that commit isn't... I'll add it now so it goes into what is likely to be 2.7.0 baring a reason for a RC3...
