### PR TITLE
fix(cpn): logical switch global variable compare range

### LINKED ISSUE #7005: Global variables initial value can be outside configured range
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

This issue applies to b&w, colour radios and Companion but not in all places due to the different UI edit methods.

Setting a GV range such that the min is > 0 or max < 0 is not always honoured. Generally the default will be 0 which falls outside the range.

When the value is edited the range limits will kick in at some point depending on whether the value is being incremented or decremented.

Changing the valid range does not trigger a check and update of all usage or at minimum warning that there could be values outside the new range.

### Expected Behavior

GV configured ranges are honoured.

### Steps To Reproduce

Flight/drive modes switching GV from linked mode to own value sets the initial value to 0.

Special functions adjust GV initially 0 or change GV# and previous GV value remains even if outside new GV range.

### Version

2.11.4

### Transmitter

Other (Please specify below)

### Operating System (OS)

_No response_

### OS Version

_No response_

### Anything else?

Checked MT12 and TX16S

### PR DESCRIPTION
**Pull request by elecpower**
Partially Fixes #7005 and some housekeeping

Applies to 2.11, 2.12 and 3.0

### CODE REVIEW

File: companion/src/modeledit/logicalswitches.cpp [hunk 1]
```diff
@@ -403,6 +403,22 @@ void LogicalSwitchesPanel::updateLine(int i)
...
+            mod = true;
+          } else if (value > range.max) {
+            value = round((range.max - range.offset) / range.step);
+            mod = true;
+          }
+
+          if (mod) {
+            model->logicalSw[i].val2 = value;
+            emit modified();
+          }
```
Comment (pfeerick) [inline companion/src/modeledit/logicalswitches.cpp]: If it doesn't make it more confusing, you can use a ternary operator to remove the need for flags... ie. 
```suggestion
if (value < range.min || value > range.max) {
  value = (value < range.min) 
    ? round((range.min - range.offset) / range.step)
    : round((range.max - range.offset) / range.step);
  model->logicalSw[i].val2 = value;
  emit modified();
}
```

Just a suggestion, whatever works best ;) There is also a `std::clamp` that came in in C++ '17, but lets not go there just yet. 🤭

**Comment by philmoz** [comment]
I don't think this will work correctly for the ABS and DELTA logical switch functions.

For ABS allowable range must always be positive.
For DELTA allowable range should be between (min - max) and (max - min).
For ABS DELTA allowable range should be between 0 and (max - min).

**Comment by elecpower** [comment]
> I don't think this will work correctly for the ABS and DELTA logical switch functions.
> 
> For ABS allowable range must always be positive. For DELTA allowable range should be between (min - max) and (max - min). For ABS DELTA allowable range should be between 0 and (max - min).

Yes and UI widget minimum and maximum also need fixing for these functions too

**Comment by elecpower** [comment]
I'm still testing the latest commit and trying to fix the lack of value acceleration.

**Comment by elecpower** [comment]
Testing complete subject to someone finding me out. Tried many approaches and asked Google but to date unable to solve the lack of value Acceleration.
