### PR TITLE
fix(color): popup warning may block UI and key input, effectively freezing radio.

### LINKED ISSUE #6643: Frsky X12S deadlocks with no way to shutdown when ext antenna not connected but selected
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

FrSky Horus X12S ISRM Tx running 2.11.3 "Jolly Mon". 

When I choose to enable the external antenna, but without it connected, a warning pops up.
After this, the Tx is frozen with the warning displayed. Its not possible to dismiss it. It is not possible to shutdown.
A long press of the power key brings up the initial screen of the shutdown animation, but shutdown does not proceed. On releasing the power key, the popup is still there. Connecting the antenna doesn't help either. The only way I have found to restore functionality is to disconnect the battery, which is of course a pain. Maybe there is a way I'm not aware of.

I note this issue has been reported before (#3424), but was supposedly fixed and closed. From reading that I'm assuming its the same deadlock problem which has not been truly fixed by eliminating the risk altogether.

### Expected Behavior

A warning which can be dismissed.

### Steps To Reproduce

1. Ensure external antenna is disconnected.
2. Select enable external antenna
3. Not 100% reproducible. 

### Version

2.11.3

### Transmitter

FrSky X12

### Operating System (OS)

_No response_

### OS Version

_No response_

### Anything else?

Looks like a classic deadlock issue to me. The related issue mentioned it was not safe to use a popup from any thread other than the main UI thread. I'm guessing the previous fix didn't go far enough and reduce the risk of deadlock to zero.

Both of my X12S, a new one and a 10 year old upgraded one, exhibit the same behaviour.

### PR DESCRIPTION
**Pull request by philmoz**
Since the PR that reworked the OS layer & timers, it seems it is no longer safe to call sleep_ms() inside a timer callback function.

Fixes #6643

### CODE REVIEW

File: radio/src/gui/colorlcd/libui/popups.cpp [hunk 1]
```diff
@@ -88,11 +88,10 @@ void show_ui_popup()
...
-                              bool waitForClose)
+bool POPUP_WARNING_ON_UI_TASK(const char* message, const char* info)
 {
-  // if already in a popup, and we don't want to wait, ignore call
-  if (!waitForClose && ui_popup_active) return;
+  // if already in a popup, ignore call
+  if (ui_popup_active) return false;
 
   // Wait in case already in popup.
   while (ui_popup_active) {
```
Comment (raphaelcoeffic) [inline radio/src/gui/colorlcd/libui/popups.cpp]: Isn't this somehow inconsistent? In general, timer FreeRTOS callbacks are not allowed to block. That includes anything that triggers putting the task to sleep. So I believe subsequent `sleep_ms` needs to go away as well.

**Comment by raphaelcoeffic** [comment]
@philmoz in case we still have anything blocking in any FreeRTOS timer callback, that needs to go. Btw. wouldn't it be preferable to post to some async event queue to trigger the warnings?

**Comment by philmoz** [comment]
> @philmoz in case we still have anything blocking in any FreeRTOS timer callback, that needs to go. Btw. wouldn't it be preferable to post to some async event queue to trigger the warnings?

Old code that I don't have a radio for testing with - so I am loathe to change it.

**Comment by pfeerick** [comment]
> Old code that I don't have a radio for testing with

PXX1 / PXX2 with RAS, so basically some FrSky radios only (and here, colour)? If it were B&W, I have the X9D+2019 if you do want to go there, otherwise, Raphael just volunteered himself as he can get access to an X12 🤪

**Comment by pfeerick** [comment]
@philmoz Is this actually relevant for 2.11? We are still using `RTOS_WAIT_MS()` there, not `sleep_ms()`, since #5840 is 3.0 only.

**Comment by philmoz** [comment]
> @philmoz Is this actually relevant for 2.11? We are still using `RTOS_WAIT_MS()` there, not `sleep_ms()`, since #5840 is 3.0 only.

Yes, 2.11 suffers from the same problems. RTN key will not close the popup and cannot shutdown radio when popup is active.

Let me know if you need a separate PR.

**Comment by pfeerick** [comment]
That would be best, otherwise it will be a few days before I can change
this over for 2.11. Thanks!
