### PR TITLE
fix(bw): Channel Monitor view not working correctly on startup

### LINKED ISSUE #4467: [MT12]  Can't switch between CHANNELS MONITOR and MIXERS MONITOR
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

After starting MT12, the display on the mixers monitor screen is incorrect.

https://www.dropbox.com/scl/fi/m8p30or93bgvzw99hqj9j/VID_20231226_201326.mp4?rlkey=6siq120uyq0rmyvnn271tavyf&dl=0

Once, go to the setup screen, it will be displayed correctly.

### Expected Behavior

It should display correctly even after startup.

### Steps To Reproduce

Go to the setup screen.

### Version

Nightly (Please give date/commit below)

### Transmitter

RadioMaster MT12

### Operating System (OS)

_No response_

### OS Version

_No response_

### Anything else?

Firmware : mt12-fbe06b3.bin

### PR DESCRIPTION
**Pull request by philmoz**
Fixes #4467 

If the 'Channels Monitor' is the start view (or is selected after startup), the view opens on the 'Mixers Monitor' instead and the ENTER key cannot be used to change view. 

User must enter a setup menu and return to the main view for the channel monitor to work correctly.

On startup - the view is not initialised correctly.

### CODE REVIEW

File: radio/src/tasks.cpp [hunk 1]
```diff
@@ -52,6 +52,11 @@ TASK_FUNCTION(menusTask)
 
   mixerTaskInit();
 
+#if !defined(COLORLCD)
+  // Ensure correct init on B&W if starting on 'Channels Monitor' page.
+  pushEvent(EVT_ENTRY);
```
Comment (raphaelcoeffic) [inline radio/src/tasks.cpp:57]: We should probably really start splitting the UI handling code cleanly so it does not spread to such places.

**Review by raphaelcoeffic — APPROVED** [review]

**Comment by pfeerick** [comment]
I think this may be hiding rather than fixing this issue. i.e. you'll find the exact same thing will still happen with this PR (and prior to it) if you start up the radio *without* the mixes/channel monitor as the startup view. First time you press enter when the mixes monitor is up it will not switch to channel monitor, until you switch to a model/radio menu and back.

**Comment by philmoz** [comment]
The root of the problem is the reusableBuffer contains stuff after startup and it does not get cleared unless the first event is EVT_ENTRY on the channels monitor view.

The channels monitor is only using 3 bytes from the reusableBuffer, so probably better to make this local static data in the channels monitor view.

**Comment by philmoz** [comment]
I've moved the channels monitor state out of the reusableBuffer so it should work on startup regardless of initial view.

Tested on X7S.

**Review by raphaelcoeffic — APPROVED** [review]

**Comment by pfeerick** [comment]
Thanks... working good on startup, when switched to after startup, or when accessed via mixer screen on Pocket.
