### PR TITLE
fix(tx16s): turn on aux2 power when used for BT

### LINKED ISSUE #5352: Uart 2 not powered when Radiomaster TX16 has bluetooth enabled using cloud build of 2.10.2 with Bluetooth flag set.
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

I have flashed my TX16S with firmware compiled through the cloud builder. I went to hardware and enabled bluetooth with a Trainer option. The Gnd and 5V pins on Aux 2 are not registering power. Aux 2 is the right hand 5 pin port. 

### Expected Behavior

I should see 5V on the 5V pin when Bluetooth is enabled.

### Steps To Reproduce

Flash 2.10.2 with Bluetooth = Yes.
Go to radio setup, Hardware. Enable Bluetooth, select Telemetry.
Measure 5v pin on Aux with multimeter or note how ESP32 is unpowered!  As Spock said: "Its dead, Jim"

### Version

2.10.2

### Transmitter

RadioMaster TX16S / TX16SMK2

### Operating System (OS)

_No response_

### OS Version

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by 3djc**
Enable/disable BT power on radio that remap AUX2 with power pin (introduced with stdperif removal)

Fixes #5352

### CODE REVIEW

**Comment by marcdornan** [comment]
I assume when this gets merged I can use it by doing a Cloud Compile of Nightly?

**Comment by 3djc** [comment]
If/when it gets merged yes. Unsure if cloud build allow you to compile PR

**Comment by marcdornan** [comment]
Don't think so. I can wait. Thx.

File: radio/src/targets/horus/hal.h [hunk 1]
```diff
@@ -1057,6 +1057,9 @@
   #define BT_USART_GPIO                 GPIOG
   #define BT_TX_GPIO                    GPIO_PIN(GPIOG, 14) // PG.14
   #define BT_RX_GPIO                    GPIO_PIN(GPIOG, 9)  // PG.09
+#if defined(RADIO_TX16S)
+  #define BT_PWR_GPIO                   GPIO_PIN(GPIOB, 0) // PB.00
+#endif
```
Comment (pfeerick) [inline radio/src/targets/horus/hal.h:1062]: Is this not also needed for T16?

**Comment by pfeerick** [comment]
I don't think we can blame StdPeriph #5023 this time this affects 2.10.x (and 2.9.x I think) as well, not just 2.11 ;)

File: radio/src/targets/horus/hal.h (hunk 1 above)
Comment (3djc) [reply radio/src/targets/horus/hal.h:1062]: Unsure, do they have external aux port ?

**Comment by 3djc** [comment]
> I don't think we can blame StdPeriph #5023 this time this affects 2.10.x (and 2.9.x I think) as well, not just 2.11 ;)

Indeed, got confused with the multi flash issue

File: radio/src/targets/horus/hal.h (hunk 1 above)
Comment (pfeerick) [reply radio/src/targets/horus/hal.h:1062]: No, but reading through the CMake defines, they presently seem to be the only other horus radio to have AUX2 enabled except when when bluetooth, and *do* have facility for a bluetooth module to be added... 
image

Comment (3djc) [reply radio/src/targets/horus/hal.h:1062]: Ok, that's a different thing, tx16s does have similar pad, and they work without this PR, as they are supplied with permanent +5v. This PR is for cases where the 'external' aux2 port is used instead of internal pads

Comment (pfeerick) [reply radio/src/targets/horus/hal.h:1062]: Ok, thanks... Well, just need that other French dude to say he's happy with this and then can include in 2.10.3 also :)

File: radio/src/bluetooth.cpp [hunk 2]
```diff
@@ -413,6 +413,15 @@ void Bluetooth::wakeup()
...
 
+#if defined(BT_PWR_GPIO)
+  if (g_eeGeneral.bluetoothMode == BLUETOOTH_OFF) {
+    bluetoothDisable();
+    state = BLUETOOTH_STATE_OFF;
+    wakeupTime = now + 10; /* 100ms */
+    return;
+  }
+#endif
+
```
Comment (pfeerick) [inline radio/src/bluetooth.cpp:424]: What was the rationale for this change? Given the immediately following code will disable it and set the wake time if it is either supposed to be OFF, or configured as trainer but trainer not enabled (although it doesn't seem to actually power .

Comment (3djc) [reply radio/src/bluetooth.cpp:424]: It looks that way, but no (hence the return statement): the BT loop assumes the module is always on (since it is hardwired this way in the radio) and runs it even if configured to off. This ensure the power port is set to off and not turned on back again for TX16s. That may be an issue for users having the internal frsky bt module, not fully sure how that module behaves

Comment (pfeerick) [reply radio/src/bluetooth.cpp:424]: I think I see it now, it is somehow related to the initial state, as without this check if you turn it off, it _will_ turn off , but without this check, it will always turn on at power on, rather than honour the configured "off" state. Thanks for clarifying wanted to separate between the ENable pin and PWR pin also ;)

**Comment by pfeerick** [comment]
@raphaelcoeffic Any concerns or complaints from the peanut gallery before reviewing privileges get yanked? :rofl:
