### PR TITLE
Clear internal RF module settings if radio level setting changed

### LINKED ISSUE #1299: Changing radio settings hardware internal module doesn't update each existing model internal rf mode
**Describe the bug**
Radio settings changing hardware internal module does reset / update each existing model internal rf mode or warn they are incompatible.

**To Reproduce**
Steps using RM TX16S sim
Edit Internal module in hardware settings say from MULTI to CRSF and exit
Open an existing model setup
Go to Internal Rf and mode is for previous internal module along with all the supporting settings.
Click on the mode value and the drop down selection is only those compatible with new internal module.

**Expected behaviour**
At the time of changing the hardware internal module reset every model internal rf mode to OFF or warn that the model settings are incompatible.

**Screenshots**
screenshot_tx16s_21-12-27_08-01-48

**General information**
 - EdgeTX version main branch
 - Hardware simulated RM TX16S

### PR DESCRIPTION
**Pull request by pfeerick**
Resolves #1299 

Ensures if you change the internal module at the radio level, that the currently active model internal rf settings are cleared, thus inhibited. This is not needed on model load, as there is a model load check which inhibits the dissimilar settings being made active. 

Summary of changes:
- On colorlcd, if you chose an option for the internal protocol other than the current one, the active model level setting is cleared  - so you can view the list and abort or re-select the current internal module without loosing any settings.
- On B&W, as soon as you scroll to see any other internal protocol other than the currently selected one, the active model level setting is cleared. Due to how the menu is displayed, you can't view the list without the setting being cleared. 

Tested on both TX16S and TX12.

### CODE REVIEW

File: radio/src/gui/common/stdlcd/radio_hardware.cpp [hunk 1]
```diff
@@ -528,11 +528,21 @@ void menuRadioHardware(event_t event)
 
 #if !defined(PCBX9D) && !defined(PCBX9DP) && !defined(PCBX9E)
       case ITEM_RADIO_HARDWARE_INTERNAL_MODULE:
-        g_eeGeneral.internalModule =
-            editChoice(HW_SETTINGS_COLUMN2, y, STR_INTERNAL_MODULE,
-                       STR_INTERNAL_MODULE_PROTOCOLS,
-                       g_eeGeneral.internalModule, MODULE_TYPE_NONE,
-                       MODULE_TYPE_MAX, attr, event, isInternalModuleSupported);
+        reusableBuffer.radioHardware.internalModule =
```
Comment (raphaelcoeffic) [inline radio/src/gui/common/stdlcd/radio_hardware.cpp:531]: If you put brackets around the case like this:
```
case ITEM_RADIO_HARDWARE_INTERNAL_MODULE: {
   .... [you code] ...
} break;
```

You should not need the reusable buffer, which makes only sense if the data is shared between multiple places, which is clearly not the case.

File: radio/src/gui/common/stdlcd/radio_hardware.cpp [hunk 2]
```diff
@@ -528,11 +528,21 @@ void menuRadioHardware(event_t event)
...
+            g_eeGeneral.internalModule;
+        reusableBuffer.radioHardware.internalModule = editChoice(
+            HW_SETTINGS_COLUMN2, y, STR_INTERNAL_MODULE,
+            STR_INTERNAL_MODULE_PROTOCOLS,
+            reusableBuffer.radioHardware.internalModule, MODULE_TYPE_NONE,
+            MODULE_TYPE_MAX, attr, event, isInternalModuleSupported);
+        if (reusableBuffer.radioHardware.internalModule !=
+            g_model.moduleData[INTERNAL_MODULE].type) {
+          storageDirty(EE_MODEL);
```
Comment (raphaelcoeffic) [inline radio/src/gui/common/stdlcd/radio_hardware.cpp:540]: Shouldn't this be *after* `memclear()`?

File: radio/src/gui/colorlcd/radio_hardware.cpp [hunk 3]
```diff
@@ -330,10 +330,17 @@ void RadioHardwarePage::build(FormWindow * window)
...
-  auto internalModule =
-      new Choice(window, grid.getFieldSlot(1, 0), STR_INTERNAL_MODULE_PROTOCOLS,
-                 MODULE_TYPE_NONE, MODULE_TYPE_COUNT - 1,
-                 GET_SET_DEFAULT(g_eeGeneral.internalModule));
+  auto internalModule = new Choice(window, grid.getFieldSlot(1, 0),
+      STR_INTERNAL_MODULE_PROTOCOLS, MODULE_TYPE_NONE, MODULE_TYPE_COUNT - 1,
+      GET_DEFAULT(g_eeGeneral.internalModule),
+      [=](int moduleType) {
+        if (!isInternalModuleAvailable(moduleType)) {
+          memclear(&g_model.moduleData[INTERNAL_MODULE], sizeof(ModuleData));
```
Comment (raphaelcoeffic) [inline radio/src/gui/colorlcd/radio_hardware.cpp:338]: Shoudn't be checked if `g_model.moduleData[INTERNAL_MODULE].type != moduleType` before clearing it? I'm not sure the *set* function is not called even the value has not changed.

File: radio/src/gui/common/stdlcd/radio_hardware.cpp (hunk 2 above)
Comment (pfeerick) [reply radio/src/gui/common/stdlcd/radio_hardware.cpp:540]: Yeah, that would be a good idea... guess that only worked because of the delay timeout thingy

File: radio/src/gui/common/stdlcd/radio_hardware.cpp (hunk 1 above)
Comment (pfeerick) [reply radio/src/gui/common/stdlcd/radio_hardware.cpp]: Thanks, that's gone now. Really shouldn't have been writing code at 1AM :-O

**Comment by pfeerick** [comment]
B&W corrections still seem to work as expected in `simu` and on T-Pro hardware. colorlcd will be in a hour or so as afk.

File: radio/src/gui/colorlcd/radio_hardware.cpp (hunk 3 above)
Comment (pfeerick) [reply radio/src/gui/colorlcd/radio_hardware.cpp:338]: The set function is still called, but given the second test of isInternalModuleAvailable() 
```
if (g_eeGeneral.internalModule != moduleType) 
return false;
```
since the selected moduleType didn't change from what already set, it correctly skipped the clear. Regardless, that is clearer, doesn't have any extra stuff that could come back to bite me, and basically the same as the B&W test so will do that. :)

**Review by raphaelcoeffic — APPROVED** [review]
