### PR TITLE
Streamlined the SPI audio init of EL18.

### LINKED ISSUE #2729: EL18 has a lot of sound clicks during power on
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

When switching on the radio, the speaker has a lot of sound clicks before the.welcome sound is played.  Seems the audio code init code has some problem that did not switch off the amplifier during initialization.

### Expected Behavior

The speaker should produce no clicks before playing the welcome sound.

### Steps To Reproduce

1. Switch on the radio
2. Multiple clicks are heard before the welcome sound is played.

### Version

Nightly (Please give date/commit below)

### Transmitter

Flysky EL18

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by richardclli**
Fixes #2729

Summary of changes:

### CODE REVIEW

**Comment by richardclli** [comment]
Can minimize multiple click sounds.

File: radio/src/targets/nv14/audio_spi_driver.cpp [hunk 1]
```diff
@@ -355,6 +357,8 @@ void audioSendRiffHeader()
   audioSpiWriteBuffer(RiffHeader, sizeof(RiffHeader));
 }
 
+#if defined(PCBX12S) || defined(PCBNV14)
```
Comment (pfeerick) [inline radio/src/targets/nv14/audio_spi_driver.cpp:360]: Isn't this a NV14-specific driver? Just wondering why there are `#if defined(PCBX12S)` headers... maybe some cleanup is needed?

Comment (gagarinlg) [reply radio/src/targets/nv14/audio_spi_driver.cpp:360]: Ther is a bunch of those scattered around in the NV14 code. Obviously someone either planned to merge this stuff together or did no bother to do a clean up after copying the files for a new target.

Comment (pfeerick) [reply radio/src/targets/nv14/audio_spi_driver.cpp:360]: I suspect the latter... think this is all basically from the openflysky fork of opentx for the nv14, and the stuff was probably just copied and hammered into shape and then left alone.

Comment (Eldenroot) [reply radio/src/targets/nv14/audio_spi_driver.cpp:360]: Maybe open a new ticket for this just to track that some day it will require cleanup

Comment (richardclli) [reply radio/src/targets/nv14/audio_spi_driver.cpp:360]: Well, what I tried to do is to use as much code from horus audio spi driver as possible to do this PR, so that we can do a merge in next release.  I do not want to change anything in horus related target, because I want to have this merge in 2.8.0 as a quick fix.  I will work out a merge after 2,8,0 release.

Comment (richardclli) [reply radio/src/targets/nv14/audio_spi_driver.cpp:360]: For other NV14 specific drivers, I will take a look and see what can be merged in next release.  Well, I have quite familiar with all these codes and will try to unify them based on Raphael's new drivers.

**Comment by pfeerick** [comment]
Nice, this also removes the clicks when hanging the volume level :)

**Comment by pfeerick** [comment]
Welp... hit shift enter instead of enter when updating merge commit msg... so an interesting commit msg now 😆
