### PR TITLE
NV14: Deadzone option

### LINKED ISSUE #1756: NV14 Throttle and Rudder issue
Using mode 2, throttle and Rudder issue. I found in the Channel Monitor the appearance that the throttle and rudder seem to stick or was stiff just a bit compared to the Elevator and Aileron which was very smooth and appeared to have no problem, looking at the graphics representation and with stick control. Reference report #1630. 
I then found that the throttle set to at about ¼ throttle speed movement the Rudder stick left or right and you got interference with the Throttle of the motor slowing down. I thought it may be Beta flight or Inav, software related, so I changed from flight controllers to the standard Receiver FS-iA6B. 

To Reproduce; I perform this test 6 times plus to reproduce the error. I then tried with the throttle position higher and was able to hear a difference in tone change when moving the Rudder stick left or right and the motor slowing down. Note; that when you bring the Rudder stick back to centre the motor returns back to its correct speed. Also it may be related to reference #1605 
I am using a T-motor and T-motor ESC matched. 

Expected behavior: Moving the Rudder stick left or right should not interfere with the Throttle position or performance of the motor (basic standard setup)

I like Edgetx.

General information
EdgeTX "Black Pearl" v2.7.0-RC1
FLYSKY NV14 
FS-iA6B

### PR DESCRIPTION
**Pull request by pfeerick**
Summary of changes:
- adds deadzone option from open-flysky/Flysky-OpenTX-Test-Branch to radio firmware
- teaches Companion about it enough to not nuke the radio setting

~~Currently, untested.~~ Is now upgraded to status of "deadzone works, but monkey implementing settings storage screwed up". Weekend problem. 

Also, radio hardware option would probably be better as a `Choice` rather than `NumberEdit` since it is limited to 7 options. However, it should be sufficient to see if this is the resolution. 

May resolve #1756

### CODE REVIEW

**Comment by Ktr128** [comment]
I compiled edgetx with deadzone.
Deadzone works great!!! )) Didn't notice any problems.

But there are problems with saving the settings.
On reboot, the settings are lost:
- voice language spontaneously set to Czech;
- switches SG on toggle;
-switches SH to none.

**Comment by pfeerick** [comment]
Well, I can update "Currently, untested. " to "Tested, but settings borked". 🤪 Thanks for the feedback... it's probably in how I modified the yaml struct to save the setting... I was honestly surprised it let me just add add it without spitting the dummy... so have to play with that tomorrow or Sunday.

**Comment by Ktr128** [comment]
I agree with you, you can add that it was tested and bugs were found while saving the settings.
Compiled with both nightly build and v2.7.0-rc1...
I tried to help you, look at the YAML struct, but I didn’t find anything wrong there.
But this is not surprising, because I'm a "great" programmer, only monkeys from the zoo are taller than me)))))))

File: radio/src/datastructs_private.h [hunk 1]
```diff
@@ -887,6 +887,9 @@ PACK(struct RadioData {
   NOBACKUP(uint8_t  imperial:1);
   NOBACKUP(uint8_t  disableRssiPoweroffAlarm:1);
   NOBACKUP(uint8_t  USBMode:2);
+  #if defined(STICK_DEAD_ZONE)
+  NOBACKUP(uint8_t  stickDeadZone:3);
```
Comment (raphaelcoeffic) [inline radio/src/datastructs_private.h:891]: @pfeerick you cannot add 3 bits just like that ;-) you need to make sure the 5 others are somewhere, otherwise the generator won’t see them.

Comment (pfeerick) [reply radio/src/datastructs_private.h]: Thanks. Fixed, and also added the check for the struct size as that was missing for the NV14

File: radio/src/mixer.cpp [hunk 2]
```diff
@@ -461,6 +476,27 @@ void evalInputs(uint8_t mode)
     if (v < -RESX) v = -RESX;
     if (v >  RESX) v =  RESX;
 
+#if defined(STICK_DEAD_ZONE)
+    //dead zone invented by FlySky in my opinion it should goes into ADC
+    //float calculations are not efficient
+    if(g_eeGeneral.stickDeadZone && ch != THR_STICK){
+    if(v > P_OFFSET)
+    {
```
[the remark this answers is not in the document]
Comment (pfeerick) [reply radio/src/mixer.cpp]: Yes, of course...

**Comment by Ktr128** [comment]
P.S. Don't kick me hard )) I'm still at the beginning of the EdgeTX journey.
But dug with a shovel along the right vector
https://github.com/Ktr128/edgetx/pull/4/files

**Comment by Ktr128** [comment]
Is there a need to check #1777 on NV14 now?

**Comment by raphaelcoeffic** [comment]
> Is there a need to check #1777 on NV14 now?

It should work now with the latest changes. But I think we should avoid adding the extra byte if we can avoid it: there are some padding bits (implicit) at the end of the structure.

**Comment by pfeerick** [comment]
@Ktr128 I'm off to bed now, but I'm hoping the next build is looking more like final state if you want to give it a spin...

**Comment by Ktr128** [comment]
> @Ktr128 I'm off to bed now, but I'm hoping the next build is looking more like final state if you want to give it a spin...
Goodnight!
When the need arises to test, I will be happy to help you.

**Comment by pfeerick** [comment]
@raphaelcoeffic I think this raises a couple of points to discuss... 
- Was this the right way to settle down the tests? 
- Is setting a small deadzone (value 2, so 4) by default when deadzone feature enabled how we want it?
- Placement of the option - I opted to place it directly under the stick naming options since it was stick related, but I am wondering if it should be moved down next to ADC filter... (and it's now a Choice BTW, rather than NumberEdit)?
image

**Comment by Ktr128** [comment]
If the user's point of view is appropriate at this stage...
I quickly found the Deadzone location, despite expecting it to be in an old location that I knew about earlier. Therefore, from my point of view, you can leave the current one.
From the point of view of the beauty of the interface, I think half-width is better.
P.S. The main thing is that the dead zone is alive again! ))

**Comment by pfeerick** [comment]
> If the user's point of view is appropriate at this stage...

IMO it's the most important view! 😄 You have to use it, after all... if the option being there was quickly found, sounds like it is in the right place. And I'm more inclined towards half-width also... seems consistent and it's not like the width is needed.

**Comment by Ktr128** [comment]
Compiled the firmware with the latest release of the Dead Zone.
Everything works! 👍

I suggest renaming the pull request "Live Zone"! 😄

**Comment by elecpower** [comment]
@pfeerick would you like me to finish the Companion side (Hardware and Print) for you?

**Comment by pfeerick** [comment]
Oops... Nearly forgot that... Yes please! But please hold off until I check in with Raphael on status of PR incase I need to change radio side...

**Comment by pfeerick** [comment]
@elecpower All good... go for it... it's staying as it is.

**Comment by elecpower** [comment]
> @elecpower All good... go for it... it's staying as it is.

Try this out and advise if needs tweaking

**Comment by pfeerick** [comment]
No tweaking necessary... reading, changing and writing new value works perfectly... thanks! :)

File: radio/src/storage/storage_common.cpp [hunk 3]
```diff
@@ -98,6 +98,11 @@ void postRadioSettingsLoad()
     g_eeGeneral.internalModule = DEFAULT_INTERNAL_MODULE;
   }
 #endif
+#if defined(STICK_DEAD_ZONE)
+  if (!g_eeGeneral.stickDeadZone) {
+    g_eeGeneral.stickDeadZone = DEFAULT_STICK_DEADZONE;
+  }
+#endif
```
Comment (pfeerick) [inline radio/src/storage/storage_common.cpp:105]: While this *does* cause deadzone to be turned back on back to "4" when set to "0", I would prefer to have it as it is now, and remove/improve this in the next version, than require all users to go in and set it. The amount of deadzone at stick center is minor, and this was the _default_ setting for the OTX fork people were using with the NV14.

Comment (tekikai) [reply radio/src/storage/storage_common.cpp:105]: Happens to me too, the settings keep reverting from 0 ot 4 on reboot of the NV14. I actually like the hypersensitivity of the sticks so I have to go back and re-set them to 0 every time I boot the radio.

I was looking for a LUA command to set the deadzone on reboot but noticed the setting only got implemented in the latest version in the first place, so maybe in a later release?

Comment (pfeerick) [reply radio/src/storage/storage_common.cpp:105]: In a later release, yet... not all settings can be changed by lua. This and ADC jitter settings are in the back of my mind to add though, particular the latter, as it can then be used in the model wizard to turn jitter filter off for multirotor.

Comment (tekikai) [reply radio/src/storage/storage_common.cpp:105]: Sounds great, looking forward to it. I opened an issue about this (did not see your reply yet) adding the 'internal RF' setting to the 'pile' ;)

**Comment by SlipstreamFPV** [comment]
Can this be added for all radios?
