### PR TITLE
fix(radio): WRONG PCB DETECTED - X10 with Touch Screen Mod

### LINKED ISSUE #6046: Radio X10 w/ Touch Screen Mod - WRONG PCB DETECTED since 2.11.0-RC1
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Since loading firmware v2.11.0-RC, all 3 versions, the FrSky X10 Series (non ACCESS)  with touch screen mod fails to start with WRONG PCB DETECTED. The only way to power down TX is remove the back cover and unplug the battery.

Returning firmware to v2.10.6 and TX will now start and operate normally.
I think I've found the problem in the updated code and working on a PR to fix.

Rich

### Expected Behavior

TX to start and operate.

### Steps To Reproduce

Load any version of 2.11.0-RC firmware on the X10 with Touch Screen Mod.
Start Radio - WRONG PCB DETECTED screen

### Version

2.11.0-rc

### Transmitter

FrSky X10 / X10S (ACCST)

### Operating System (OS)

_No response_

### OS Version

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by MRC3742**
Fixes #6046

WRONG PCB DETECTED error on X10 with Touch Screen Mod.
Since updates to new GPIO driver ported from RIOT-OS in PR 5023 was merged.

Small corrections to detect proper PCBREV on these radios with the added touch screen.

Thanks to pfeerick for his help on solving this problem. :smiley:
@pfeerick please review and squash before merge.

Rich

### CODE REVIEW

**Comment by MRC3742** [comment]
commit added: PCBREV pin define for the FrSky X7 series radio was never changed (updated) as part of PR 5023 (chore(hal): remove StdPeriph)

**Comment by pfeerick** [comment]
@3djc Can you just double check this looks ok? Rich has been able to test the FrSky X10 configurations, and it seems the only relevant X7 revision test is for the QX7 - `PCBREV_X7_STD` vs `PCBREV_X7_40`?

File: radio/src/targets/common/arm/stm32/pwr_driver.cpp [hunk 1]
```diff
@@ -70,14 +70,10 @@ void pwrInit()
...
 #elif defined(PCBREV_GPIO_1) && defined(PCBREV_GPIO_2)
   gpio_init(PCBREV_GPIO_1, GPIO_IN_PU, GPIO_PIN_SPEED_LOW);
-  #if defined(PCBREV_TOUCH_GPIO)
-    #if defined(PCBREV_TOUCH_GPIO_PULL_UP)
-      gpio_init(PCBREV_GPIO_2, GPIO_IN_PU, GPIO_PIN_SPEED_LOW);
-    #else
-      gpio_init(PCBREV_TOUCH_GPIO, GPIO_IN_PD, GPIO_PIN_SPEED_LOW);
-    #endif
+  gpio_init(PCBREV_GPIO_2, GPIO_IN_PU, GPIO_PIN_SPEED_LOW);
+  #if defined(PCBREV_TOUCH_GPIO_PULL_UP)
```
Comment (3djc) [inline radio/src/targets/common/arm/stm32/pwr_driver.cpp:74]: What if not defined ? I guess we could something in hall.h like:
#define PCBREV_TOUCH_PULL_TYPE  GPIO_IN_PD or GPIO_IN_PU
and here 
 gpio_init(PCBREV_TOUCH_GPIO, PCBREV_TOUCH_PULL_TYPE, GPIO_PIN_SPEED_LOW);

Comment (MRC3742) [reply radio/src/targets/common/arm/stm32/pwr_driver.cpp:74]: I don't believe that "#if defined" and associated "#endif" are needed as it falls under the previous "#elif defined(PCBREV_GPIO_1) && defined(PCBREV_GPIO_2)" or the "#define" for it is not needed in the hal.h file. Previous code needed this distinction, current code does not.
It could just be moved below the GPIO_2 init line ?
It compiles fine as I've listed above and works as it should on the x10 series of radios.

Also line 70, "hardwareOptions.pcbrev = PCBREV_VALUE();" could be removed as it is repeated and would be executed in current code line 81 ? 

Rich

Comment (pfeerick) [reply radio/src/targets/common/arm/stm32/pwr_driver.cpp:74]: This is **assuming** `PCBREV_TOUCH_GPIO_PULL_UP` (or similar) will always be nested... what JC is suggesting is restoring the code to what was probably it's original intent... where it either pulled up or down...
```cpp
elif defined(PCBREV_GPIO_1) && defined(PCBREV_GPIO_2)
  gpio_init(PCBREV_GPIO_1, GPIO_IN_PU, GPIO_PIN_SPEED_LOW);
  gpio_init(PCBREV_GPIO_2, GPIO_IN_PU, GPIO_PIN_SPEED_LOW);
  #if defined(PCBREV_TOUCH_GPIO_PULL_UP)
    gpio_init(PCBREV_TOUCH_GPIO, GPIO_IN_PU, GPIO_PIN_SPEED_LOW);
  #else
    gpio_init(PCBREV_TOUCH_GPIO, GPIO_IN_DN, GPIO_PIN_SPEED_LOW);
  #endif
```
but then also further making it simpler replacing `PCBREV_TOUCH_GPIO_PULL_UP` with  `PCBREV_TOUCH_PULL_TYPE`

```cpp
  #elif defined(PCBREV_GPIO_1) && defined(PCBREV_GPIO_2)
    gpio_init(PCBREV_GPIO_1, GPIO_IN_PU, GPIO_PIN_SPEED_LOW);
    gpio_init(PCBREV_GPIO_2, GPIO_IN_PU, GPIO_PIN_SPEED_LOW);
    #if defined(PCBREV_TOUCH_GPIO)
      gpio_init(PCBREV_TOUCH_GPIO, PCBREV_TOUCH_PULL_TYPE, GPIO_PIN_SPEED_LOW);
    #endif
```  

This more generic form *might* then be useful in the future? :shrug:

> Also line 70, "hardwareOptions.pcbrev = PCBREV_VALUE();" could be removed as it is repeated and would be executed in current code line 81 ?

Most definitely **not**! Line 70 will _only_ be executed on `#elif defined(PCBREV_GPIO)` whereas line 81 will _only_ be executed on `#elif defined(PCBREV_GPIO_1) && defined(PCBREV_GPIO_2)` i.e. one is for single GPIO revision indicator, other is for two GPIO revision indicator.

Comment (pfeerick) [reply radio/src/targets/common/arm/stm32/pwr_driver.cpp]: @3djc is #cad076c what you were thinking?

Comment (MRC3742) [reply radio/src/targets/common/arm/stm32/pwr_driver.cpp]: And this is why you get that big paycheck at the end of the week! :laughing:

Seriously now, after your current commits, tested and still working on the X10 Series Radios.
Thanks for the input and explanations - Rich

Comment (pfeerick) [reply radio/src/targets/common/arm/stm32/pwr_driver.cpp]: Wait... what? WE GET PAID? I've been robbed all this time... I'mma gonna have words with the management!! :zany_face: 

Thanks for the confirm/retests... much appreciated. Now to see if JC is happy enough with the current state :hand_over_mouth:

Comment (3djc) [reply radio/src/targets/common/arm/stm32/pwr_driver.cpp]: Yes indeed, many a catchall is missing:in hal.h (I haven't check if defined for all radio)
#if !defined(PCBREV_TOUCH_PULL_TYPE)
#define PCBREV_TOUCH_PULL_TYPE GPIO_IN_PD

or a compilation stop if not define
#if !defined(PCBREV_TOUCH_PULL_TYPE)
static_assert("bla bla");

Comment (pfeerick) [reply radio/src/targets/common/arm/stm32/pwr_driver.cpp]: Don't give me choices!! :laughing: Ok, how about about option 1, with some compile time noise to encourage it to be set. I was thinking about option 2, but a #pragma error to make it kill the compile, but we don't currently do that sort of "don't be an idiot!!" check anywhere else... yet! ;)

Comment (3djc) [reply radio/src/targets/common/arm/stm32/pwr_driver.cpp]: Try creating a new radio and don't input ana direction, you will see if we don't have a "don't be a JC" catch 🗡️

Comment (pfeerick) [reply radio/src/targets/common/arm/stm32/pwr_driver.cpp]: I very nearly made that a fatal '"Somebody" forgot to add PCBREV_TOUCH_PULL_TYPE, might wanna fix that' 🤣

**Comment by pfeerick** [comment]
T15 (a X10 family radio) PCB detection still working with both revisions plus RF still working on my X7 radio (unsure of the revision).
