### PR TITLE
fix(lua): io.read always reading 256 bytes rather than specified value

### LINKED ISSUE #5832: EdgeTx 2.11:  LUA io.read(file, n) always reading 256 bytes regardless of the value of "n".
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Looks like we have a bug on io.read (file, n), 
is ignoring the "n".  Works fine in 2.10.5

Image

### Expected Behavior

Should read the number of bytes asked.

### Steps To Reproduce

Looks like the issue is here:
Always reading LUAL_BUFFERSIZE instead of the parameter "n"

Image

### Version

Nightly (Please give date/commit below)

### Transmitter

RadioMaster TX16S / TX16SMK2

### Operating System (OS)

_No response_

### OS Version

_No response_

### Anything else?

Can't use GitPod.io anymore.. will try to setup a local environment to fix it.

### PR DESCRIPTION
**Pull request by frankiearzu**
Fixes #5832

Summary of changes:
Use parameter "n" instead of the fix LUAL_BUFFERSIZE

image

### CODE REVIEW

**Comment by frankiearzu** [comment]
Validated in TX16S.. Forward Programming (DSMTools) works again in 2.11

**Comment by raphaelcoeffic** [comment]
@frankiearzu This code comes straight from Lua code. I believe the intent is actually to buffer I/O ops by reading full buffer size when possible, and then returning only what you asked. You might want to check the original Lua code to see how it is actually supposed to work. Reading a couple bytes from FatFs is very ineffecient.

**Comment by raphaelcoeffic** [comment]
Nevermind, the original Lua code is doing the same:
```c
static int read_chars (lua_State *L, FILE *f, size_t n) {
  size_t nr;  /* number of chars actually read */
  char *p;
  luaL_Buffer b;
  luaL_buffinit(L, &b);
  p = luaL_prepbuffsize(&b, n);  /* prepare buffer to read whole block */
  nr = fread(p, sizeof(char), n, f);  /* try to read 'n' chars */
  luaL_addsize(&b, nr);
  luaL_pushresult(&b);  /* close buffer */
  return (nr > 0);  /* true iff read something */
}
```

File: radio/src/thirdparty/Lua/src/liolib.c [hunk 1]
```diff
@@ -425,7 +425,7 @@ static int read_chars (lua_State *L, FIL *f, size_t n) {
   luaL_Buffer b;
   luaL_buffinit(L, &b);
   p = luaL_prepbuffsize(&b, n);  /* prepare buffer to read whole block */
-  if (f_read(f, p, LUAL_BUFFERSIZE, &nr) != FR_OK) nr = 0; /* try to read 'n' chars */
+  if (f_read(f, p, n, &nr) != FR_OK) nr = 0; /* try to read 'n' chars */
```
Comment (arkarkark) [inline radio/src/thirdparty/Lua/src/liolib.c:428]: do you not want to read the MAX of n and LUAL_BUFFERSIZE to avoid buffer overflows?

Comment (pfeerick) [reply radio/src/thirdparty/Lua/src/liolib.c:428]: Don't you mean the *MIN* of the two? 🤭  To prevent overflow you want it to be n, unless n exceeds, at that point it should be constrained to LUAL_BUFFERSIZE . i.e. `if (n > LUAL_BUFFERSIZE) n = LUAL_BUFFERSIZE;`

This might also be a question to put to the Lua developers also, as this is their unmodified code (i.e. c.f. https://www.lua.org/source/5.3/liolib.c.html). Maybe they assumed you won't be using `read_chars()` for long stuff. In our case that would be probably 512 bytes, rather than the 8192 bytes (in some cases) they use have `LUAL_BUFFERSIZE` set to.

Comment (philmoz) [reply radio/src/thirdparty/Lua/src/liolib.c:428]: luaL_prepbuffsize resizes the buffer to the second parameter (n in this case) if needed.
So there is not chance of buffer overflow.

Comment (pfeerick) [reply radio/src/thirdparty/Lua/src/liolib.c:428]: Except n still isn't being constrained to LUAL_BUFFERSIZE, though, no? And luaL_prepbuffsize is also checks LUAL_BUFFERSIZE when not explicitly given a upper boundary, and would fail at the `/* not enough space? */` comment. So you can still resize the buffer to larger than the buffer constraint size?

Comment (arkarkark) [reply radio/src/thirdparty/Lua/src/liolib.c:428]: Great, sorry for the confusion and yeah, of course MIN! Ha, this is why they don’t let me code any more

Comment (pfeerick) [reply radio/src/thirdparty/Lua/src/liolib.c:428]: > 'n' doesn't need to be constrained.

So you are saying n = 784 should be valid input, when LUAL_BUFFERSIZE is 256, rather than be constrained to the configured buffer size?

Comment (philmoz) [reply radio/src/thirdparty/Lua/src/liolib.c:428]: Yes. LUAL_BUFFERSIZE is just a default value that will be used if luaL_prepbuffsize is not called, or n <= LUAL_BUFFERERSIZE.

Comment (philmoz) [reply radio/src/thirdparty/Lua/src/liolib.c:428]: If you look at the comments in the Lua discord channel that started this, he was trying to read nearly 10K.

Comment (pfeerick) [reply radio/src/thirdparty/Lua/src/liolib.c:428]: > LUAL_BUFFERSIZE is just a default value that will be used if luaL_prepbuffsize is not called

Fair enough, I was clearly interpreting it wrongly to be the buffer size limit, not just a default. Thank you for clearing that up.
