### PR TITLE
fix(AFHDS3): Sync UI with Flysky AFHDS3 module stored settings

### LINKED ISSUE #3491: Flysky IRM301 and FRM303 model settings are not in sync with UI
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Changing model will not have the UI model settings sync properly with the settings in the (int/ext) module.

### Expected Behavior

1. UI change receiverID -> TX get config -> refresh UI
2. UI change options -> TX set config
3. model load -> TX get config -> refresh UI

### Steps To Reproduce

1. Create at least 2 model with 2 receivers
2. Bind them
3. Wwitch between model

### Version

Nightly (Please give date/commit below)

### Transmitter

Flysky EL18

### Operating System (OS)

_No response_

### OS Version

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by richardclli**
Fixes https://github.com/EdgeTX/edgetx/issues/3491, fixes https://github.com/EdgeTX/edgetx/issues/3477 (reworked), fixes https://github.com/EdgeTX/edgetx/issues/3682

Summary of changes:

- [x] UI change receiverID -> TX get config -> refresh UI
- [x] UI change options -> TX set config
- [x] model load -> TX get config -> refresh UI
- [x] receiver connected -> options that is only changeable in bind will be disabled for edit

### CODE REVIEW

**Comment by philmoz** [comment]
It would need some way to reset the flag otherwise the UI will keep updating.

It think it would be better to just store the get_tmr10ms() when a change is made to the module that needs a UI update.
Then the UI code can use this to see if a refresh is needed, and no reset is needed (the UI code just compares the last refresh time to the last module changed time).

**Comment by philmoz** [comment]
PR #3502 has code to update the module window if the module refresh time changes. You should be able to merge that PR into your branch.

Note: I have no way to test this so I can't guarantee it will work.

Also, to avoid unnecessary updates, the module code should take care to only update the 'lastModuleUpdatedTime' value when the underlying module data has actually changed.

**Comment by richardclli** [comment]
Thank you, I will check and see later when I have access to my radios.

**Comment by pfeerick** [comment]
This appears to be working for EL18 - changing receiver ID now triggers a UI refresh when different receivers have different settings, which also means the RF mode (Fast 8Ch, Routine 18Ch etc) is updating to correctly reflect different receiver profiles.

**Comment by richardclli** [comment]
> This appears to be working for EL18 - changing receiver ID now triggers a UI refresh when different receivers have different settings, which also means the RF mode (Fast 8Ch, Routine 18Ch etc) is updating to correctly reflect different receiver profiles.

Nice, now need to check how the change of options can update a connected receiver.

**Comment by pfeerick** [comment]
> Nice, now need to check how the change of options can update a connected receiver.

If it truely is runtime, and you refer to the options like servo frequency, purpose of the NP#  ports, etc, that update action could perhaps be triggered as you exit the screen - which I think is similar to how R9M Access, ISRM, etc do it.

**Comment by richardclli** [comment]
> > Nice, now need to check how the change of options can update a connected receiver.
> 
> If it truely is runtime, and you refer to the options like servo frequency, purpose of the NP# ports, etc, that update action could perhaps be triggered as you exit the screen - which I think is similar to how R9M Access, ISRM, etc do it.

I think I will try to add hooks to the UI that will mark the config as dirty and update the config during normal operation cycles.

**Comment by richardclli** [comment]
@philmoz seems the refreahing logic will stop other modules from refreshing properly, e.g. MPM

**Comment by richardclli** [comment]
> > seems the refreahing logic will stop other modules from refreshing properly, e.g. MPM
> 
> I don't understand - can you provide more details on what is happening.

The MPM status is not refreshed with this change i.e. MPM version no. is not shown, just white.

I found that MPM has timestamp to control the refresh.

https://github.com/EdgeTX/edgetx/blob/main/radio/src/telemetry/multi.cpp#L254-L257

Let me check the code of other modules first.  I think we need a unified mechanism to control options refresh in UI.

**Comment by richardclli** [comment]
@philmoz I finally got it right.  Overriding checkEvents need to call super class method otherwise there will be something missing for the children.

https://github.com/EdgeTX/edgetx/blob/764ec3e5255a3e2b07984398b1d1a67d37554c9f/radio/src/gui/colorlcd/flysky_settings.cpp#L94-L99

Thanks for your code that enlighten me.

**Comment by richardclli** [comment]
Now the settings can change online.  Need some time for people to test.  Flysky will help to test as well.

**Comment by richardclli** [comment]
@raphaelcoeffic I have change some state flow in the AFHDS3 state machine, please help me to review to see if there maybe any loop holes.

File: radio/src/hal/module_port.h [hunk 1]
```diff
@@ -145,10 +145,16 @@ inline uint8_t modulePortGetType(const etx_module_driver_t& d) {
 }
 
 inline const etx_serial_driver_t* modulePortGetSerialDrv(const etx_module_driver_t& d) {
+#if defined(SIMU)
+  if (d.port == nullptr) return nullptr;
+#endif
```
Comment (raphaelcoeffic) [inline radio/src/hal/module_port.h:150]: It's probably worth adding this code even for non-simu, IMHO.

File: radio/src/hal/module_port.h [hunk 2]
```diff
@@ -145,10 +145,16 @@ inline uint8_t modulePortGetType(const etx_module_driver_t& d) {
...
   return d.port->drv.serial;
 }
 
 inline const etx_timer_driver_t* modulePortGetTimerDrv(const etx_module_driver_t& d) {
+#if defined(SIMU)
+  if (d.port == nullptr) return nullptr;
+#endif
```
Comment (raphaelcoeffic) [inline radio/src/hal/module_port.h:157]: Here as well.

File: radio/src/hal/module_port.h (hunk 1 above)
Comment (richardclli) [reply radio/src/hal/module_port.h:150]: This is changed by @philmoz instead, any comments.

File: radio/src/hal/module_port.h (hunk 2 above)
Comment (richardclli) [reply radio/src/hal/module_port.h:157]: This is changed by @philmoz instead, any comments.

Comment (philmoz) [reply radio/src/hal/module_port.h:157]: I added these checks to stop the simulator from crashing. I suspect it's because the simulator does not have a real module and the initialisation is not the same a on a real radio; but I did not dig very deeply into it.

Comment (raphaelcoeffic) [reply radio/src/hal/module_port.h:157]: Sure, but we could still add these checks whether we're on SIMU or not, right? Do you guys see any downside?

**Comment by richardclli** [comment]
@raphaelcoeffic @philmoz Any more reviews and comments?

BTW, I have delivered firmware with this PR for users in China.  Up to now, it seems the changes works well and stable.

**Comment by philmoz** [comment]
Nothing obvious leaps out at me.

File: radio/src/hal/module_port.h (hunk 2 above)
Comment (richardclli) [reply radio/src/hal/module_port.h:157]: I will change it anyway, check always there.

Comment (richardclli) [reply radio/src/hal/module_port.h]: @raphaelcoeffic Changed as per your request.

**Comment by pfeerick** [comment]
It seems like I did something right there :grin:

image

**Review by pfeerick — APPROVED** [review]
There is more work to be done for AFHDS2/3, but this PR seems to do what it says on the tin ;) Settings saved to file now also survive a read/write pass through Companion. They cannot be fully configured with Companion yet, as it seems we need to purge FRM302 related entries before we can fully match the FRM303 in Companion... but one problem at a time.
