### PR TITLE
Use COLOR_THEME_PRIMARY1 as a default lua script color

### LINKED ISSUE #1134: wrong color assignment in some widget elements, size of "Channels"
while playing around with themes i figured out that the bars in "channels" have a wrong color-assignment, like the ForeColor in Mike Shellim's "Showall" V 0.9.8 (latest)

My Theme:
screen-2021-11-22-210610
There is no blue at all...

Widget "Channels"
screen-2021-11-22-211237

Widget "Showall":
screen-2021-11-22-211303

for comparsion same on OTX:
screen-2021-11-22-152055

screen-2021-11-22-152136

As U may also notice, in ETX Widget "Channels" is cut on the Bottom compared to OTX, even without Trims etc...

screen-2021-11-22-154116

And the "Batt-Value" in the Top-Bar on ETX is black and not changeable, on OTX it's the same color like the rest in the Top-Bar, which looks like it should be... my 2ct...

Maybe someone else figured all that out long before me, if so pls close the case...

THX

### PR DESCRIPTION
**Pull request by eshifri**
Fixes #1134 at least partially

Summary of changes: if lua script uses colorFlag==0 use PRIMARY1 color instead of default color.
The change effects lua scripts only.

### CODE REVIEW

**Comment by pfeerick** [comment]
Unfortunately that is the quickest way to turn the screen black! 😇 😆 

Just in case it wasn't clear... that don't work!

File: radio/src/lua/api_colorlcd.cpp [hunk 1]
```diff
@@ -60,8 +60,11 @@ LcdFlags flagsRGB(LcdFlags flags)
   // RGB or indexed color?
   if (flags & RGB_FLAG)
     return flags;
-  else
-    return (flags & 0xFFFF) | COLOR(COLOR_VAL(flags)) | RGB_FLAG;
+
+  if (!(flags & 0xFF))
```
Comment (pfeerick) [inline radio/src/lua/api_colorlcd.cpp:64]: I dunno if it's the right way to do it... but when I initially looked at this... `if (flags == 0)` seemed to work.

**Comment by pfeerick** [comment]
Having said that, I think I found another hinky bug... BLUE is not BLUE 😆 

```lua
local function run(event)
  lcd.clear()

  lcd.drawText(1, 0, "WHITE", WHITE)
  lcd.drawText(1, 20, "BLACK", BLACK)
  lcd.drawText(1, 40, "RED", RED)
  lcd.drawText(1, 60, "GREEN", GREEN)
  lcd.drawText(1, 80, "BLUE", BLUE)
  lcd.drawText(1, 100, "DEFAULT")

  lcd.drawText(80, 0, "WHITE", lcd.RGB(255,255,255))
  lcd.drawText(80, 20, "BLACK", lcd.RGB(0,0,0))
  lcd.drawText(80, 40, "RED", lcd.RGB(255,0,0))
  lcd.drawText(80, 60, "GREEN", lcd.RGB(0,255,0))
  lcd.drawText(80, 80, "BLUE", lcd.RGB(0,0,255))
  lcd.drawText(80, 100, "DEFAULT")

  lcd.drawText(1,120,"BLUE = " .. lcd.getColor(BLUE))

  if event == EVT_VIRTUAL_ENTER_LONG or
     event == EVT_ENTER_LONG or
     event == EVT_MENU_LONG then
      -- exit script
      return 2
  end

  return 0
end

return {run=run}
```

**Comment by jfrickmann** [comment]
Oops! I will include a commit in #978 since I am working on the same source code file there.

File: radio/src/lua/api_colorlcd.cpp (hunk 1 above)
Comment (eshifri) [reply radio/src/lua/api_colorlcd.cpp:64]: Flags include font size information as well, so if(flags == 0) has no effect if font size is not zero.

Comment (jfrickmann) [reply radio/src/lua/api_colorlcd.cpp:64]: I thing that there is a much simpler solution:
https://github.com/EdgeTX/edgetx/blob/d775e75e81b35ea2729ef053ce34e205b6a967e4/radio/src/gui/colorlcd/colors.h#L29-L49
Delete `DEFAULT_COLOR_INDEX`, and now `COLOR_THEME_PRIMARY1_INDEX` is the new default!

Comment (jfrickmann) [reply radio/src/lua/api_colorlcd.cpp:64]: Of course, you need to grep for `DEFAULT_COLOR_INDEX` and replace a couple of appearances in the themes.

Comment (eshifri) [reply radio/src/lua/api_colorlcd.cpp:64]: I thought about it, but I'm not sure: I suspect the DEFAULT_COLOR_INDEX, was introduced for some corner cases, when the color table was not initialized yet (bootloader?). Since I do not know original considerations, I'm reluctant to do this "drastic" change. If anybody is sure this will not create problems - of course this is a cleaner solution.

Comment (jfrickmann) [reply radio/src/lua/api_colorlcd.cpp:64]: The bootloader does not use theme color (I know, because when I did, Raphael told me to not mess ever with that again 🤣)  I don't see any problems getting rid of `DEFAULT_COLOR_INDEX`. Here is the output from grep:
```
radio/src/gui/colorlcd/theme_manager.cpp:  if (i >= COLOR_COUNT) return DEFAULT_COLOR_INDEX;
radio/src/gui/colorlcd/theme_manager.cpp:  if (colorIndex >= DEFAULT_COLOR_INDEX && colorIndex < LCD_COLOR_COUNT) {
radio/src/gui/colorlcd/themes/480_default.cpp:      lcdColorTable[DEFAULT_COLOR_INDEX] = RGB(18, 94, 153);
radio/src/gui/colorlcd/themes/flysky.cpp:      lcdColorTable[DEFAULT_COLOR_INDEX] = RGB(18, 94, 153);
radio/src/gui/colorlcd/colors.h:  DEFAULT_COLOR_INDEX,
radio/src/gui/colorlcd/colors.h:#define COLOR(index) ((uint32_t)lcdColorTable[unsigned(index & 0xFF) >= LCD_COLOR_COUNT ? DEFAULT_COLOR_INDEX : unsigned(index & 0xFF)] << 16u)
```
As you can see, it is only used a few times (and they should probably be removed anyway).

Comment (eshifri) [reply radio/src/lua/api_colorlcd.cpp:64]: I will give it a try

Comment (eshifri) [reply radio/src/lua/api_colorlcd.cpp]: Actually, both variants do not work.
Now I understand the first comment: the font is always black now.

**Comment by jfrickmann** [comment]
Please see #1155

**Comment by eshifri** [comment]
Does it work for you?
I defined 
#define DEFAULT_COLOR_INDEX COLOR_THEME_PRIMARY1_INDEX
and foreground is always black.

**Comment by jfrickmann** [comment]
Yes, it seems to work just fine. Please test the firmware build on #1155, or give me a test script, then I will post a screenshot from the simu.

**Comment by eshifri** [comment]
I'm using showAll for testing (it is in the widgets folder).

**Comment by jfrickmann** [comment]
> I'm using showAll for testing (it is in the widgets folder).

I do not have it, nor do I see it here: https://github.com/EdgeTX/edgetx-sdcard/tree/master/sdcard/horus/WIDGETS

**Comment by eshifri** [comment]
[SHOWALL.zip](https://github.com/EdgeTX/edgetx/files/7605339/SHOWALL.zip)

**Comment by jfrickmann** [comment]
Here it is:
showall

**Comment by eshifri** [comment]
Yes, but can you please try EdgeTX RED ?

**Comment by jfrickmann** [comment]
Yes, it is all black. But you have an all black background, and the default color is now black - so what else would you expect?

**Comment by jfrickmann** [comment]
Aha, I see it now:
```
	if bit32.btest (wgt.options["Use dflt clrs"], 1) then
		colorFlags = COLOR_THEME_PRIMARY1
	else
		lcd.setColor (CUSTOM_COLOR, wgt.options.BackColor)
		lcd.drawFilledRectangle (
			wgt.zone.x,
			wgt.zone.y,
			wgt.zone.w,
			wgt.zone.h,
			CUSTOM_COLOR)
		lcd.setColor (CUSTOM_COLOR, wgt.options.ForeColor)
		colorFlags = CUSTOM_COLOR
	end
```
Doesn't work because DEFAULT_COLOR is gone ...

**Comment by eshifri** [comment]
You are right. 
It just brings the question how some color schemes are defined.
Looks like PRIMARY1 is black more often, than not and the widget is unreadable.

But this is a separate problem.
I think your solution is good!
I will close this PR.

**Comment by eshifri** [comment]
Oh, no, this is my recent experiment. You can put it to 0 - this means default color.
The result is the same since DEFAULT==PRIMARY1 now.

**Comment by jfrickmann** [comment]
OK! Please note that you can easily change the background with e.g. `lcd.clear(COLOR_THEME_PRIMARY2)`.

**Comment by eshifri** [comment]
Yes, it is working as designed.
The problem is some widgets that were OK in OTX (e.g. SHOWALL) may become invisible in EdgeTX in certain color schemes.
So the burden goes onto shemes designers. :-)

**Comment by pfeerick** [comment]
Well, in the case, I would expect the default for functions like `drawText()` to be `PRIMARY1` (label text) where not specified (, and the default for `clear()` to be `SECONDARY3` (Main screen's background) if not specified... the former I expect is the case now, but the latter would be a pain...

**Comment by pfeerick** [comment]
If a basic script (like the one in the third comment of this PR) _has_ to specify the colours for clear and/or `drawText` to be legible, then it's unusable as far as I'm concerned. The defaults should be legible ;)

**Comment by eshifri** [comment]
static int luaLcdClear(lua_State * L)
{
  if (luaLcdAllowed && luaLcdBuffer) {
    LcdFlags flags = luaL_optunsigned(L, 1, COLOR2FLAGS(COLOR_THEME_SECONDARY3_INDEX));
    flags = flagsRGB(flags);
    luaLcdBuffer->clear(flags);
  }
  return 0;
}

So the intention is correct. The result - not so much. :-)

**Comment by jfrickmann** [comment]
Last time that I checked, clear() worked as it should. No argument will show the background picture, and a color argument will turn the screen that color.

**Comment by pfeerick** [comment]
Keep in mind this plays with widgets AND standalone ;)

**Comment by pfeerick** [comment]
Right, so this PR as it stands right now is not working properly, and is actually breaking something else quite badly => Theme defined PRIMARY1 is being forced black. i.e. use FM2M Vineyard from the SD card pack - it should be green label text, not black. And more than a few themes change the colour from black - quite a few set it to white. 

EventDemo widget is black text, lines and square, instead of PRIMARY1

EventDemo standalone is white BG (that's fine, it's configured white), but black text/lines/rectangle. 

Colour test standalone script mentioned above - `lcd.clear()` used SECONDARY2, not SECONDARY3 - perhaps it's out by one now? And of course, `BLUE` is not blue, but `lcd.RGB(0,0,255)` is blue; )

image

**Comment by eshifri** [comment]
I think the last commit fixies foreground color issue.
lcd.clear() works correctly: if cold without argument sets background color to COLOR_THEME_SECONDARY3.
The problem with showall is it does not call clear, when default colors are used.

**Comment by pfeerick** [comment]
That seemed to get it :) I did a nasty RGB test theme at one point, and this is showing PRIMARY1 default text colour and SECONDARY3 default clear now :) And generally widgets and standalone lua are following theme colours now. Just that pesky blue for Jesper to solve now 😁 

snapshot_07

**Comment by jfrickmann** [comment]
I included that in #1154 since it is editing the same file: https://github.com/EdgeTX/edgetx/pull/1154/commits/6c2371f9fae97692910a201bd6158c1fb13e4af3

**Comment by pfeerick** [comment]
Thanks :) Does the change in this PR seem ok? It appears to be working in the limited tests I've done.

**Comment by eshifri** [comment]
Which PR we are talking about hre? :-)
This one or #1154?

**Comment by pfeerick** [comment]
This one 1154 is unrelated ;)

**Comment by eshifri** [comment]
I think this one works as it should now.
