### PR TITLE
fix: Ext module not powered when using SBUS or CPPM trainer

### LINKED ISSUE #3634: External module bay not powered when using trainer/sbus or trainer/cppm
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

When using a CPPM outputing receiver in module bay for wireless training, you need power for the receiver, available normaly on BAT pin, but that pin is not currently powered.

Since selecting a module to power bay as a workaround disables trainer/sbus and trainer/cppm, there is no workaround

Was working in 2.8.x

### Expected Behavior

External module BAT pin should powered

### Steps To Reproduce

Turn off external module, select either Trainer/SBUS or Trainer/CPPM, module bay BAT pin is not powered.

### Version

Nightly (current, haven't git bisect)

### Transmitter

RadioMaster TX12 / TX12MK2, FrSky X7 and I suspect many others

### Operating System (OS)

_No response_

### OS Version

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by bug400**
Fixes #3634 

Summary of changes:
Power on/off of the external module is now in the module init/deinit code. Since trainer/sbus and trainer/ccpm are no modules,  power on/off is not handled for that mode of operation. Therefore, moduleSetPower calls were added to the init/deinit subroutines for trainer/sbus and trainer/cppm. There is also a fix in stop_trainer_module_sbus() where sbus_trainer_mod_st has to be set to nullptr after deiniztialization of the sbus port.

Tested on QX7-ACCESS with edgetx 2.9.1 with mode trainer/sbus (with SBUS data source and power pin voltage check) and with mode trainer/sbus (power pin voltage check only, I do not have a ccpm data source).

### CODE REVIEW

File: radio/src/targets/common/arm/stm32/trainer_driver.cpp [hunk 1]
```diff
@@ -371,6 +376,8 @@ void stop_trainer_module_sbus()
 {
   if (!sbus_trainer_mod_st) return;
   modulePortDeInit(sbus_trainer_mod_st);
+  modulePortSetPower(EXTERNAL_MODULE,false);
+  sbus_trainer_mod_st= nullptr;
```
Comment (raphaelcoeffic) [inline radio/src/targets/common/arm/stm32/trainer_driver.cpp:380]: May I buy an empty space before `=`?

Comment (raphaelcoeffic) [reply radio/src/targets/common/arm/stm32/trainer_driver.cpp]: Thx!

**Comment by pfeerick** [comment]
This should have been targeted against the main branch, but will be messy to change, so can be cherry-picked into `main` afterwards.

**Comment by raphaelcoeffic** [comment]
> This should have been targeted against the main branch, but will be messy to change, so can be cherry-picked into main afterwards.

I force-pushed the cherry-picked code now based on `main` onto his branch ;-)

**Comment by BergWolfRC** [comment]
Thanks for providing this fix.
On my TX1S MKII with EdgeTX 2.9.1 I encountered specifically the problem that the external module was not powered when using CPPM trainer.
Now, with EdgeTX 2.9.4 installed I do get the power for the external module in this case.
However the PPM signal of the receiver connected to the external module bay (PPM via Pin 2) is not recognized by the TX even if trainer special function is enabled (set to sticks). Could this be another side effect of the changes in the code?
I am using a cm410X as receiver in the trainer tx for receiving the student signals (servo attached to the RX does move).

**Comment by BergWolfRC** [comment]
thanks for double checking, confirming and creating the follow up issue!
You guys rock!
