### PR TITLE
Warn on connected model (#1466)

### LINKED ISSUE #1466: No warning when changing connected model
**Describe the bug**
Was reported here: https://www.rcgroups.com/forums/showthread.php?3023832-UndergroundFPV-Dark-Knight-Radio/page283
for NV14, but the problem is common for all colorLCD TXs:
there is no warning (alarm) message when a user selects "change model" while the current model is still powered on and connected.

**To Reproduce**
Power up current model.
Go to "select model" and chose another model.
The model will be changed without a warning that the current model "is still connected".

**Expected behavior**
An alarm should be risen.

**General information**
 - EdgeTX current 2.7 
 - Hardware NV14 and RM TX16S
 
Looks like this functionality is not implemented for color lcd TXs.

### PR DESCRIPTION
**Pull request by eshifri**
Fixes #1466 
This PR adds a warning "Model is still connected" when user attempts to select a new model (on color LCD TXs).

Summary of changes: audio message and confirmation dialog are added.

### CODE REVIEW

**Comment by pfeerick** [comment]
I've made it so that pressing return at the confirmation stops the model change - as it continued on before. Also, I believe the disableRssiPoweroffAlarm condition check should have been AND, not OR. Please give it a try and see what you think.

**Comment by Nerenye** [comment]
> I've made it so that pressing return at the confirmation stops the model change - as it continued on before. Also, I believe the disableRssiPoweroffAlarm condition check should have been AND, not OR. Please give it a try and see what you think.
> 
> It is convoluted, but in most places in the code it is initial a check of TELEMETRY_STREAMING (or sometimes disableRssiPoweroffAlarm), and then a check of the other. And then it changes to checking the state of either after that initial trigger.

I think "OR" could be valid because non telemetry receivers probably are not streaming telemetry.

File: radio/src/gui/colorlcd/model_select.cpp [hunk 1]
```diff
@@ -208,22 +208,25 @@ class ModelCategoryPageBody : public FormWindow
           Menu *menu = new Menu(parent);
           if (model != modelslist.getCurrentModel()) {
             menu->addLine(STR_SELECT_MODEL, [=]() {
-              // we store the latest changes if any
+              bool modelConnected = TELEMETRY_STREAMING() &&
```
Comment (Nerenye) [inline radio/src/gui/colorlcd/model_select.cpp:211]: I think "OR" could be valid because non telemetry receivers probably are not streaming telemetry.

**Comment by eshifri** [comment]
This is "philosophy change" :-)
I thought that if user disabled RSSI alarm, he is taking responsibility and model is "not connected" no matter what.
I also thought that confirmation means user wants to proceed with changing the model no matter what. Otherwise he has to power the current model down.
I do not know which approach is "correct", but they are different.

**Comment by pfeerick** [comment]
Pressing RTN when the warning is shown isn't confirmation though is it. Before your PR would show the warning and regardless of off you press ENT (confirm) or RTN (abort) it would change models....this now changes models only when you confirm ;)

I'll have a look at the RSSI again, I had already double checked the truth tables and thought OR would show the warning when it shouldn't in one case, but it still didn't feel right. Might have to nest it properly instead like done on B&W (IE if not RSSI warning disabled, now check telemetry streaming).

**Comment by eshifri** [comment]
Makes sense. I forgot about RTN - had touch screen (NV14) in mind. :-)

File: radio/src/gui/colorlcd/model_select.cpp (hunk 1 above)
Comment (pfeerick) [reply radio/src/gui/colorlcd/model_select.cpp:211]: I don't think so in this instance, as OR would also trigger when there is no telemetry and setting is disabled, because it is an inverted test. 

Please check to see if I missed something (note: I'm taking into account real end state of test ... having `!` and not having `!`. However, the more practical test is on hardware, and it _seems_ to be working as intended... with telemetry active, confirm warning shows, with RSSI warning disabled and telemetry active, no confirm warning, no telemetry, no confirm warning. 
```
TELEMETRY_STREAMING() && !disableRssiPoweroffAlarm  | 
1                     &&  1 (not disabled)          | T
1                     &&  0 (disabled)              | F
0                     &&  1 (not disabled)          | F
0                     &&  0 (disabled)              | F


TELEMETRY_STREAMING() || !disableRssiPoweroffAlarm  | 
1                     ||  1 (not disabled)          | T
1                     ||  0 (disabled)              | T
0                     ||  1 (not disabled)          | T
0                     ||  0 (disabled)              | F


TELEMETRY_STREAMING() ||  disableRssiPoweroffAlarm  | 
1                     ||  1 (disabled)              | T
1                     ||  0 (not disabled)          | T
0                     ||  1 (disabled)              | T
0                     ||  0 (not disabled)          | F
```

Comment (eshifri) [reply radio/src/gui/colorlcd/model_select.cpp:211]: I think your code is correct.

**Comment by pfeerick** [comment]
Ok, I've just run this through on TX16S and NV14, and I think it is working as expected/intended ;) 

Specifically: 
- if you have a telemetry receiver active, and RSSI power off warning is enabled, you will get the confirmation screen
- if you have a telemetry receiver active, and RSSI power off warning is **disabled**, you will not get the confirmation screen
- if you have a non-telemetry receiver active (or have disabled telemetry - MPM), and RSSI power off warning is enabled, you will not get the confirmation screen
- if you have a non-telemetry receiver active (or have disabled telemetry - MPM), and RSSI power off warning is disabled, you will not get the confirmation screen
- in the case where the confirmation screen is shown, only touching in the arrow, or pressing enter, will confirm/continue, touching anywhere else or press RTN will abort back to model select screen

If someone else could double check this that would be appreciated :)

File: radio/src/gui/colorlcd/model_select.cpp (hunk 1 above)
Comment (pfeerick) [reply radio/src/gui/colorlcd/model_select.cpp:211]: Phew... I have always hated truth tables when combined with inversions... so always a chance stuffed it up ;) Thanks! :)

**Comment by Nerenye** [comment]
> * if you have a non-telemetry receiver active (or have disabled telemetry - MPM), and RSSI power off warning is enabled, you will not get the confirmation screen

is that a typo? If RSSI Power off warning is enabled it should show the confirmation right?

**Comment by pfeerick** [comment]
Confirmation of what, since there's no telemetry :laughing:

**Comment by Nerenye** [comment]
We´ll ... my bad. xD

Already compiling. Reporting my results later

**Comment by pfeerick** [comment]
Thanks. If you don't pick anything up, this will get merged and will probably wrap up 2.6. No pressure ;)

**Comment by Nerenye** [comment]
- [X] > * if you have a telemetry receiver active, and RSSI power off warning is enabled, you will get the confirmation screen
- [X] > * if you have a telemetry receiver active, and RSSI power off warning is **disabled**, you will not get the confirmation screen
- [X] > * if you have a non-telemetry receiver active (or have disabled telemetry - MPM), and RSSI power off warning is enabled, you will not get the confirmation screen
- [X] > * if you have a non-telemetry receiver active (or have disabled telemetry - MPM), and RSSI power off warning is disabled, you will not get the confirmation screen
- [ ] > * in the case where the confirmation screen is shown, only touching in the arrow, or pressing enter, will confirm/continue switching models, touching anywhere else or press RTN will abort back to model select screen

Can´t Check the touch event though .. i´m missing the touchscreen

If you Lose telemetry while the confirmation screen is shown it will immediately switch to the new model
That Should be fixed!

**Comment by pfeerick** [comment]
Hm... that was intentional right from the start... i.e. if you disconnect the power to the model, the reason for blocking the model select is gone... just like with powering off the radio... you'll notice if you pull the plug on the receiver the radio will turn off (if it was sat at the model still connected prompt)... and this behavior has always been like that. 

But at the same time, I would want to ask "why where you trying to change models when your plane flew out of range?" :grin:

**Comment by Nerenye** [comment]
> If you Lose telemetry while the confirmation screen is shown it will immediately switch to the new model
> That Should be fixed!

Well thats probably another stupid thought... we can´t know if the model is powered down or if we´ve just lost telemetry.....
Maybe we could add a delay.  if you lose telemetry it usually reconnects within a second... If were not back up within 1,5 seconds we´ll proceed as if the model is powered down.

**Comment by Nerenye** [comment]
> But at the same time, I would want to ask "why where you trying to change models when your plane flew out of range?" 😁

I didn´t. But you probably mean the issue opener.

Besides my suggestion for handling lost tele, it works like intended. 

+1

**Comment by gagarinlg** [comment]
> Well thats probably another stupid thought... we can´t know if the model is powered down or if we´ve just lost telemetry.....
> Maybe we could add a delay. if you lose telemetry it usually reconnects within a second... If were not back up within 1,5 seconds we´ll proceed as if the model is powered down.

So you want a delay when the telemetry is lost, before the dialog goes away? Sounds reasonable. Maybe this can then also be integrated into the power off check.

**Comment by Nerenye** [comment]
> > Well thats probably another stupid thought... we can´t know if the model is powered down or if we´ve just lost telemetry.....
> > Maybe we could add a delay. if you lose telemetry it usually reconnects within a second... If were not back up within 1,5 seconds we´ll proceed as if the model is powered down.
> 
> So you want a delay when the telemetry is lost, before the dialog goes away? Sounds reasonable. Maybe this can then also be integrated into the power off check.

I´ve never switched models while the model was powered and connected and probably never will. 
But in case it does happen it would prevent accidentally switching models. 
If its not to much efford i would ship it with delay.

**Comment by pfeerick** [comment]
That wouldn't be a bad idea at all... same for the radio power down screen... as an added confidence check. 

@gagarinlg I'm running away off to bed now... any chance you could shoehorn some delay code into the radio powerdown in another PR, and then I can copy that across to here? I think I know roughly how I would implement it... just not sure of the specifics since I'm not sure how you measure time in RTOS land ... I'll shut up and go to sleep as you probably know a better way :)

**Comment by Eldenroot** [comment]
There should be some notice to user if you dont use telemetry... confirmation with model lost or something like that.

**Comment by eshifri** [comment]
@Eldenroot Can you please clarify your suggestion? 
If there is no telemetry, we do not know the model is still connected.
If user disabled RSSI warning - this is what he wanted (although I cannot imagine why somebody will do that).

**Comment by pfeerick** [comment]
Havn't looked at this in depth yet but nice work! 

I'm in to minds on no telemetry condition... I'm conscious of there being a problem switching models in that instance, but I also don't want this to end up where you have so many warning screens it becomes a hazard in itself. At some point we need to stop holding the users hand and they be accountable for their own actions. In other words, I would strongly suggest shouldn't be playing in model select screen at all with powered up model.

**Review by pfeerick — APPROVED** [review]
Just a minor cosmetic change, but I think this will do for now. We probably need to look into the telemetry streaming stuff a bit more, as I think it has it's own 1 second timeout, and maybe a bit more sluggish with certain protocols as well... i.e. Flysky seemed slower for transmitter to acknowledge telemetry recovered, although control link was immediately re-established. Frsky seemed better. Was good onTX16S (colorlcd) and TPro (B&W) - I could blip the receiver power and transmitter wouldn't shutdown or switch models unless it was an overly long interval.

**Comment by eshifri** [comment]
I think for NV14 telemetry is being read about once per second; do not know whether this is TX or RX.

**Comment by Eldenroot** [comment]
Spektrum radios for example

When you wanna change model or do whatever with internal or external module tx - change protocol etc, you are warned about connection lost between you and the model.

It is quite useful and it could prevent to lost model or hurt somebody.

**Comment by pfeerick** [comment]
It really depends of what generation of Spektrum radio you have... for instance my DX6i does not prompt at all when switchign model, whereas DX6 2nd gen turns the RF off before letting you alter most of those settings. 

However, this can certainly be considered in a separate issue and pull request, as this is getting out of scope of this PR. And I would suggest it be done as an *optional* feature.

**Comment by Nerenye** [comment]
Need me to test it again?

**Comment by pfeerick** [comment]
If you're bored, otherwise you get to test it after tomorrow with everyone else since it'll be in the next nightly unless something comes up...

**Comment by Nerenye** [comment]
Nahh I'm good 😅
