### PR TITLE
view text functionality restored

### LINKED ISSUE #2057: text view is broken
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

In the current 2.8 code ViewTextWindow class does not work for both TX and simulator.
Naturally, pre-flight notes are also broken.

Minor issue: here https://github.com/EdgeTX/edgetx/blob/ebcd61f68625ccacdc352491dc5f4ddb9ea1ef6f/radio/src/gui/colorlcd/radio_sdmanager.cpp#L240
WARN_FILE_LENGTH is 16, so a warning is given for every gile longer than 16 bytes.

Major problems are in the view_text.cpp:
1. The text is loaded from the file (I have validated it with TRACE() ), but the screen remains empty.
2. With commented out onTouchSlide() and checkEvents()
https://github.com/EdgeTX/edgetx/blob/ebcd61f68625ccacdc352491dc5f4ddb9ea1ef6f/radio/src/gui/colorlcd/view_text.cpp#L111
there is no way to traverse the text that is bigger than one screen (Tested with TRACE() )
The commented out code cannot be re-enabled, since Window::focusWindow does not exist any more. 

### Expected Behavior

Text file of any size should be displayed by view_text.

### Steps To Reproduce

1. Go to Radio Setup ->SD Card.
2. Select a text file.
3. Select view.
4. The Warning Window will pop-up warning that the file size is 0.
5. Select display anyway.
6. Observe empty screen.

### Version

Other (Please specify below)

### Transmitter

Radiomaster TX16S

### Anything else?

Happens for every color radio and its simulator.

### PR DESCRIPTION
**Pull request by eshifri**
This PR is based on #2058 by @raphaelcoeffic 

Fixes #2057

Summary of changes: text viewer based on lvgl label object.
Viewer supports touch and roller interface.
txt and csv (log) files are supported. csv files are opened from the end. 
On the TXs with PGUP and PGDWN buttons long files can be viewed by loading additional pages.

### CODE REVIEW

File: radio/src/gui/colorlcd/view_text.cpp [hunk 1]
```diff
@@ -57,236 +42,166 @@ void ViewTextWindow::extractNameSansExt()
...
-  //     textVerticalOffset = maxLines - maxScreenLines;
-  //   sdReadTextFileBlock(fullPath.c_str(), readLinesCount);
-  // }
-  // return Page::onTouchSlide(x, y, startX, startY, slideX, slideY);
-  return true;
+//  lv_event_code_t code = lv_event_get_code(e);
+  lv_obj_t *obj = lv_event_get_target(e);
+  if (obj) {
+    lv_group_t *g = (lv_group_t *)lv_obj_get_group(obj);
+    if (g) lv_group_set_editing(g, true);
```
Comment (raphaelcoeffic) [inline radio/src/gui/colorlcd/view_text.cpp:100]: If you remove CLICK_FOCUSABLE from the form containing the label, you won't need this, as shown by f5f453c3cb2.

Comment (eshifri) [reply radio/src/gui/colorlcd/view_text.cpp]: Thank you! Done.

**Comment by pfeerick** [comment]
Hey @eshifri this is working great with one minor caveat... it looks like there's double newlines if CRLF formatted text? If you can easily knock that off I think this is right to merge. 

[FPV250.txt](https://github.com/EdgeTX/edgetx/files/9107628/FPV250.txt) (with CRLF endings)
image

vs 

[Mobula_7.txt](https://github.com/EdgeTX/edgetx/files/9107635/Mobula_7.txt) (with LF endings)
image

**Comment by eshifri** [comment]
@pfeerick Interesting. The line, ending with dot "." causes the same effect.
This must be something in lvgl - my code does not have special handling for CR ot for "."
Let me search the Internet. :-)

**Comment by pfeerick** [comment]
Fantastic... yes, that looks like it fixed both in one hit. LF/CRLF are treated the same, and `.` endings don't have a ... I guess it was automatic newline appended.
