### PR TITLE
fix(cpn) - Fix handling of the 'show splash' setting for B&W radios in Companion.

### LINKED ISSUE #3331: Edge TX Companion 2.8.1 does not restore Show Splash Screen on Startup from file
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

When setting up the radio profile for my new Radiomaster Boxer, there is a setting for 'Show Splash Screen on Startup' with several time options, and an option to presumably disable the splash screen. However, after saving and loading the .etx file, this value is always set back to 4s (presumably the default).

image

### Expected Behavior

I would expect the setting to be saved to the file so it is not set back to the default every time.

### Steps To Reproduce

1. Start Edge TX Companion
2. Open or create a new .etx file
3. Edit the Radio Settings
4. Change the Show Splash Screen on Startup setting to something other than 4s
5. Close the Radio Settings
6. Save and close the file
7. Reopen the file
8. Edit the Radio Settings
9. Note the Show Splash Screen on Startup is set back to 4s

### Version

2.8.0

### Transmitter

Radiomaster Boxer

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by philmoz**
Fixes #3331 

Summary of changes:
- Change Companion logic for the splash screen settings to match the firmware logic.
- Only save/load splash screen settings for b&W radios.

### CODE REVIEW

File: companion/src/firmwares/opentx/opentxeeprom.cpp [hunk 1]
```diff
@@ -3088,10 +3088,8 @@ OpenTxGeneralData::OpenTxGeneralData(GeneralSettings & generalData, Board::Type
   internalField.Append(new UnsignedField<3>(this, generalData.internalModuleBaudrate));
   if (IS_FAMILY_HORUS_OR_T16(board))
     internalField.Append(new SpareBitsField<3>(this));
-  else if (IS_TARANIS(board))
-    internalField.Append(new SignedField<3>(this, generalData.splashDuration));
   else
-    internalField.Append(new UnsignedField<3>(this, generalData.splashMode)); // TODO
+    internalField.Append(new SignedField<3>(this, generalData.splashMode)); // TODO
```
Comment (pfeerick) [inline companion/src/firmwares/opentx/opentxeeprom.cpp:3092]: `// TODO` can probably go?

**Review by pfeerick — APPROVED** [review]
Seems to be working fine. The checkbox was legacy from the AVR transmitters like the 9XR-PRO which are no longer supported, so can definitely go.

**Review by elecpower — APPROVED** [review]
tested save and open etx, and on x9d+ lib sim and looks good to me
