### PR TITLE
fix(color): New inputs disappear until restart.

### LINKED ISSUE #4315: On colorlcd, leaving gaps between inputs can result in inputs not being shown or usable as sources until restart
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

On TX16 hardware and simulator, if you create a couple inputs with gaps between, they will initially be visible when adding, but when you leave the tab, they won't be shown. On restart, they *may* reappear again. 

### Expected Behavior

That the inputs still be visible (and usable)!

### Steps To Reproduce

1. Create a blank model
2. Add inputs 11, 13, 15 (just accept the default source, etc)
3. Witness them being visible. 
4. Switch to the mixer page ... try to add one of these inputs as a mixer line... it won't work 
5. Switch back to the inputs page... 11, 13, 15 are missing!
7. Restart the radio
8. The inputs are back again, and can be selected as a source on the mixes page. 

### Version

Other (Please specify below)

### Transmitter

RadioMaster TX16S / TX16SMK2

### Operating System (OS)

_No response_

### OS Version

_No response_

### Anything else?

I've not tried B&W. This affects 2.9.2 as well as nightly. Was reported on discord => https://discord.com/channels/761870396085108757/854744834698379274/1173313580620337262

### PR DESCRIPTION
**Pull request by philmoz**
Fixes #4315

Adding a new input with a gap before it to the last input would add the new to the wrong slot in the 'expos' data array.
Restarting the radio would rebuild the 'expos' array correctly.

This PR fixes ensures new inputs are added at the right spot (and cleans up the source file formatting).

### CODE REVIEW

File: radio/src/gui/colorlcd/model_inputs.cpp [hunk 1]
```diff
@@ -343,26 +358,27 @@ void ModelInputsPage::newInput()
...
-    if (EXPO_VALID(line))
+    if (EXPO_VALID(line)) {
       chn = line->chn + 1;
-    else
+      index += 1;
+    } else {
       chn += 1;
+    }
     ++line;
   }
```
Comment (pfeerick) [inline radio/src/gui/colorlcd/model_inputs.cpp:377]: Is this the section / all that needs changing (so I can pull it into 2.9 for a future release)? It's hard to tell exactly what needs changing as the formatting was done in the same commit.

Comment (philmoz) [reply radio/src/gui/colorlcd/model_inputs.cpp:377]: Yes, that's the fix. Sorry for making things harder for you.

Comment (pfeerick) [reply radio/src/gui/colorlcd/model_inputs.cpp:377]: Thanks for that. 👍 Just in future, if you think there is a good chance a fix might get back-ported, can you do the formatting in a separate commit... just makes it less likely half a fix will get pulled in (especially if needing to work around changes on both sides). 🙂

**Comment by pfeerick** [comment]
Another issue I realised that doesn't stem from the same bug, but is semi-related, is that if you say 

1. start with a blank model (so only four inputs)
2. add input 10

then when you go back to the add menu, it will let you add 5,11-32. If you add 5, it'll then let you add 6, and so on, and so on. 

2.9.1 doesn't exhibit this bug, so 2.10 only I think.

**Comment by philmoz** [comment]
I think there is a bigger problem with the PR - please don't add it to 2.9 just yet.

**Comment by pfeerick** [comment]
I actually had (and should have been paying more attention, as this introduced that odd behaviour on the 2.9 build also), but have rolled it back. For some reason, I thought the aforementioned behaviour was present in 2.10 prior to now 🤷
