### PR TITLE
fix(color): Limit label lengths, improve lbl display, prevent inv. char

### LINKED ISSUE #2282: Model labels with commas malformed against models
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion and Radio firmware

### Current Behavior

screenshot_tx16s_22-09-06_23-20-50
Screenshot from 2022-09-06 23-11-55

Same for Win 10 and Ubuntu 20.04

### Expected Behavior

Model labels match list

### Steps To Reproduce

1. Create new model file
2. Create new model
3. Amend Favorites to x,x

4. Select model
5. Select x,x label

### Version

Other (Please specify below)

### Transmitter

Radiomaster TX16S

### Anything else?

Commit [58a6239a](https://github.com/EdgeTX/edgetx/commit/58a6239a)

### PR DESCRIPTION
**Pull request by dlktdr**
- (FW) Corrects Checkall() was running twice when opening a new model. (Throttle Warning / Control Warning)
- (FW) Buffer overflow on labels too long or too many
- (CPN) Added warnings to the user if labels are too long or too many on a model in companion.
- (FW) Fix: rename create extra partial labels if a model is close to the limit
- (BOTH) Switched the commas to bullets on radio and firmware to fix #2282 
- (FW) Close model_select after making a new model
- (BOTH) Prevent YAML characters in label name. **Temporary**, will have to re-work yaml parser a bit to fully allow all characters (Will be a new PR destined for 2.9) CPN w/validator, FW, remove them.
- (FW) Limit length of text box
- (BOTH) Limit label length to 16 bytes
- (CPN) Move label up and down and rename buttons

### CODE REVIEW

File: companion/src/firmwares/radiodata.cpp [hunk 1]
```diff
@@ -106,76 +106,75 @@ void RadioData::convert(RadioDataConversionState & cstate)
...
+  int lengthdiff = csvTo.size() - csvFrom.size();
 
-  // Check that rename is possible, not too long
+  // Check that rename is possible (Rename won't cause too long of a string)
   for(auto& model : models) {
-    if((int)strlen(model.labels) + lengthdiff > (int)sizeof(model.labels) - 1) {
-      success = false;
+    if ((int)strlen(model.labels) + lengthdiff > (int)sizeof(model.labels) - 1) {
+      success = false;     
+      throw std::length_error(model.name);
```
Comment (dlktdr) [inline companion/src/firmwares/radiodata.cpp:156]: @elecpower Since radio data isn't a Q_OBJECT I can't emit a signal for a message. Are you okay with this, or should I re-work to make RadioData a Q_OBJECT and inherit it. Little more of a challenge with the use of RadioData copy constructor

Or something else...

Comment (elecpower) [reply companion/src/firmwares/radiodata.cpp:156]: Yes it should be a Q_OBJECT and this discussion came up in OTX years ago but was dropped for fear of what it would break and the time to test and fix.
I try to create all new classes as QObjects or QWidgets to take advantage of Qt framework even if they do not need if the first iteration.
You are effectively doing this with no break risk so I'm okay with your approach in the instance

**Comment by elecpower** [comment]
Long labels really screw with the radio display. Here is just a few examples:

screenshot_tx16s_22-09-07_21-18-59

Before editing the labels
screenshot_tx16s_22-09-07_21-20-52
After editing
screenshot_tx16s_22-09-07_21-23-58

screenshot_tx16s_22-09-07_21-23-12
screenshot_tx16s_22-09-07_21-21-14

On the simulator long labels also affect scrolling and selection
screenshot_tx16s_22-09-07_21-21-01

**Comment by elecpower** [comment]
Labels can be reordered on the radio with Move Up/Down but not in Companion

**Comment by dlktdr** [comment]
Been thinking about the labels length issue. I think we/I should limit the individual label length. Thinking 10 characters maximum? This will make sure every label has it's own line in the model_select and the menu's look correct.

As for the radio's resizing the text box, I'll first see if I can make it a fixed width so it won't do this. Otherwise maybe ditch showing the labels in there all together and switch it to say "Edit Labels" if that is a problem. If you select too many there isn't going to be an easy way to show them all anyway except for the menu.

Bug where it's telling you that couldn't rename on the wrong model - Will fix
As for the radio not showing that model I will figure that one out too

Moving them in companion, on the to-do list. Want to be sure all the major bugs are out and will spend some time on this in a new PR. Was going for drag drop to re-order, should there be also move up/down actions in the context menu and toolbar too, so it's like similar to the radio?

As for the checklist thing yeah, hopefully won't be too confusing. Open to other ideas here, my other initial thought was a delegate that brought up a combobox checklist in the labels column of the models. Like you said will wait and see response here.

**Comment by pfeerick** [comment]
I was going to suggest limiting the length of the labels also - as for the exact length, I'm not particularly fussed. If the label view in the model selector screen could show multi-line, it could be something wacky like around 20 characters (i.e. two lines), otherwise for some strange reason 16 comes to mind... am I stuck in an 8 bit loop? 😆 

For the model edit screen... Maybe instead of letting it just go on and on and on... make it truncate to fit the screen `...` to signify the need to press the button to see more? Maybe there is a 'fit' option rather than 'expand to infinity' option somewhere???

Move up/down buttons like on the radio would probably be the "simplest" user experience, as drag 'n drop hasn't always played nicely with Companion (overwrite vs insert, etc). Along with that pesky rename button :grin:

**Comment by elecpower** [comment]
> Been thinking about the labels length issue. I think we/I should limit the individual label length. Thinking 10 characters maximum?

I for one cannot see the need for long labels. The pain is outweighed by the gain. So a size limit similar to other name fields eg mix lines. Though no matter what max length is chosen someone will complain...

> As for the radio's resizing the text box, I'll first see if I can make it a fixed width so it won't do this. Otherwise maybe ditch showing the labels in there all together and switch it to say "Edit Labels" if that is a problem. If you select too many there isn't going to be an easy way to show them all anyway except for the menu.

I'm not sure how hard this is on the radio but how about a button with the labels as the text and should the labels exceed the max button label length truncate and add periods eg Favorites, Glid... clicking the button opens Labels Edit dialog. This way if you have one or two labels they would be visible without the need to go to the edit dialog.

> Moving them in companion, on the to-do list. Want to be sure all the major bugs are out and will spend some time on this in a new PR. Was going for drag drop to re-order, should there be also move up/down actions in the context menu and toolbar too, so it's like similar to the radio?

Drag drop nice but is flaky in Qt as shown in models list (picking the place to drop is a matter of pixels) and behaves slightly differently per OS. For simplicity context menu items which are used in other places in Companion already.

> As for the checklist thing yeah, hopefully won't be too confusing. Open to other ideas here, my other initial thought was a delegate that brought up a combobox checklist in the labels column of the models. Like you said will wait and see response here.

On the radio the labels are edited in model edit dialog so would seem logical to move to model edit in Companion and then check boxes are also filters in models list.

**Comment by dlktdr** [comment]
Sounds like you both wrote that at the same time and came to the same conclusions, so we are in agreement. Powers of two sound good, 16 it is. Should be long enough for minimal complaints 😅 

Yes, cropping the line is a great idea and easy, sold.

Ok will ditch drag drop idea, that actually makes the QTmodel easier too. and three new actions (up, down & rename😉)

> On the radio the labels are edited in model edit dialog so would seem logical to move to model edit in Companion and then check boxes are also filters in models list.

They can also be edited in the model_select screen too, hopefully everyone will find this. It's a lot quicker than opening every model you want to change. Actually contemplated removing from model_edit at one point, don't really need two methods to edit them. So I think it would still be a good idea to make it editable from the main screen in companion rather than having to open every model, like we were with able with categories. For now should I just toss a label that's explains what the checkboxes are, e.g. "Choose the labels for the selected model" right below the toolbar or below the listView? Or a tooltip at minimum?

Work just got pretty busy again but if there is enough time will try some other options. Moving the models around to customize order is also on the to-do list but not going to happen in 2.8 😞

**Comment by pfeerick** [comment]
Yup, sounds good. I prefer Companion as it is - i.e. yes, you can edit labels from the model edit screen, but also from model select screen (as well as that is where you create and order them).

**Comment by dlktdr** [comment]
What is the current stance of Unicode support in companion, I see usage of toUtf8, toLocal8Bit and toLatin1 used in the code. I'm trying to limit the total byte count to 16 but not sure on the stance here. I have a validator that limits based on UTF8 encoding as this is what LVGL supports. Is this a correct assessment.

**Comment by dlktdr** [comment]
I hearby request, Please break me some more 😄

Made the label length max 16 chars, Radio just crops, Companion strips to a UTF8 boundary max 16bytes with a validator.

model_edit show ... for too many labels, in both portrait and landscape sizes.

UTF characters don't cause oddities in companion (as far as I have tested). **Note** They do on the radio still as I'm compiled in EN here. If a UTF8 character is used they don't show (Not even as a ? character) and the text edit won't let you remove the characters on a rename.  Underlying issue. I will re-compile in another language and and test more on my side as well. I can work on this in a new PR.

Fixed the rename bug too long in companion.

Fixed rename on radio, checks all the models first, to prevent partial labels from being created. No warning to user still, another PR.

Added move up, down and rename 😉 buttons & removed the drag drop code from the QTmodel

Trying to get to the point we can do a RC, will try to fix the bugs that make it un-usable first. On to #2293 now.

**Comment by gagarinlg** [comment]
> If a UTF8 character is used they don't show (Not even as a ? character)

The fonts are reduced to the minimum charset for the used language. Maybe it is possible to define a replacement character.

**Comment by elecpower** [comment]
Companion and radio prevent quotes (and for that matter any other special characters) in label names as it stuffs up the yml files, label list, etc, etc
[D] firmwares/edgetx/edgetxinterface.cpp::writeYamlToByteArray():89 - Labels:
  1234567890123456: ~
  abc"123: ~
  Favorites: ~
  glider: ~

[D] firmwares/edgetx/edgetxinterface.cpp::writeYamlToByteArray():89 - semver: 2.8.0
header:
  name: MODEL01
  bitmap: ""
  labels: 1234567890123456,abc"123,glider

From libsim
0.39s: Labels: Updating model model1.yml
0.39s: YAML model reader
0.39s: <MODEL01/0> : 0,0,0
0.39s: <MODEL01/1> : 0,0,0
0.39s: ERROR no Current Model Found
0.39s:   - Set current model to first available

**Comment by elecpower** [comment]
Model labels still creating formatting issue with left shift of row label and box

Before edit
screenshot_tx16s_22-09-11_08-55-11


After edit
screenshot_tx16s_22-09-11_08-49-08

**Comment by elecpower** [comment]
Shorten field size, truncate or add "..." so keeps in one line.

screenshot_tx16s_22-09-11_08-58-29

**Comment by elecpower** [comment]
Cosmetic: remove "Label" text from Add and Remove buttons and context menus as unnecessary and keeps all actions consistent

Screenshot from 2022-09-11 09-03-28

**Comment by dlktdr** [comment]
> The fonts are reduced to the minimum charset for the used language. Maybe it is possible to define a replacement character.

Yes this would be a good idea, it should show something at least. Will have to add this to the todo list. 

> Companion and radio prevent quotes (and for that matter any other special characters) in label names as it stuffs up the yml files, label list, etc, etc [D] firmwares/edgetx/edgetxinterface.cpp::writeYamlToByteArray():89 - Labels: 1234567890123456: ~ abc"123: ~ Favorites: ~ glider: ~

Omg, I can't believe I haven't typed a quote in this whole time.. Thanks Neil. 👍 Of course. will escape them.

> Model labels still creating formatting issue with left shift of row label and box

Will take a few more characters off, must have tested with not so wide characters.

> Shorten field size, truncate or add "..." so keeps in one line.

Not too sure about this one, if there is unicode charaters and since it's just limited by bytes, the line can get mighty short quickly. I could add some extra parsing to shorten based on actual characters. I will leave this for a new PR. User can easily just not enter such a long name for now, shouldn't break anything, just looks off.

**Comment by dlktdr** [comment]
On the quotation issue. Apparently this isn't as easy as just escaping them. @raphaelcoeffic do you have time to add escape \ char to the yaml parser for an attribute. It currently only works for values.

Otherwise option I'm leaning towards for time being use the validator to prevent the quotes in companion, and just replace the characters if entered on the radio to something else.

FYI probably should make an issue on this I also tested writing a quote into radio's ownerid. the " doesn't get escaped. In this case only messes up that field.

On the plus side glad getting to the point of the corner cases 😉 Although they always seem to take a lot of time.

**Comment by dlktdr** [comment]
@gagarinlg I have done some (basic) searching on lvgl on the issue of what to show when a utfchar isn't available. Your experience here is far better than mine. Is this something you could help with? I don't know the solution here.

**Comment by pfeerick** [comment]
I could be barking up the wrong tree, but "escape \ char to the yaml parser for an attribute. It currently only works for values." could also overlap with this PR #1973 that a certain grinch wasn't happy with :-P I dunno why... it actually works... even though it is avoiding the root problem! 🙃

**Comment by gagarinlg** [comment]
The utf replacement character 0xFFFD is not in the pre rendered fonts. I have to check, if the font drawing part tries to use it or not.

**Comment by gagarinlg** [comment]
So, LVGL just does insert a space with the width of a "w", when a character is missing. To fix this we will have to patch LVGL and add the option to decide how to handle missing glyphs

**Comment by dlktdr** [comment]
> So, LVGL just does insert a space with the width of a "w", when a character is missing. To fix this we will have to patch LVGL and add the option to decide how to handle missing glyphs

As of right now it's supposed to leave a space? Or it can be made too? In photo below I have a (Trademark R), but it doesn't appear to leave a space at all. Here or in a text edit.

image

**Comment by pfeerick** [comment]
Since this PR has gone quiet, I'm guessing you're waiting on me now? 😆

**Comment by dlktdr** [comment]
Hey, Yes another check would be good. I think with this one in 2.8 should tide everyone over. There was that character issue still, but I don't think it's really going to be a problem.. 🙏

**Comment by pfeerick** [comment]
From some random poking and prodding on TX16S... including this lunacy on the left... it is doing well. NV14 looks OK also. Companion and Simulator generally look good. I'm sure we'll find more gremlins lurking, but that's for nightly/RC to find ;) Nice work Cliff! :)

image

**Review by pfeerick — APPROVED** [review]
