### PR TITLE
partial implementation of 354

### LINKED ISSUE #354: "Outputs" tab changes: missing trims => subtrims, copy/add subtrims phrasing
EdgeTX 2.4.0 RC3
Jumper T18

copy trims to subtrims does not work

### PR DESCRIPTION
**Pull request by kevinkoenig**
Partially fixes #354 

This PR partially implements 354. 
1. renamed menus as per JimB
2. Added Menu at top of list to Add all trims to subtrips

the other suggestions on output screen rework are not implemented.  My suggestion is to close 354 as it was created to add the Add All Trims to Subtrims and kind of exploded from there.  I would create a new issue around the output screen optimization and leave that till 2.7.

IMHO

### CODE REVIEW

File: radio/src/translations/untranslated.h [hunk 1]
```diff
@@ -330,6 +330,7 @@
 
 #define TR_USE_THEME_COLOR "Use theme color"
 
+#define TR_ADD_ALL_TRIMS_TO_SUBTRIMS "Add all Trms to Subtrims"
```
Comment (pfeerick) [inline radio/src/translations/untranslated.h:333]: Trms => Trims ;)

File: radio/src/gui/colorlcd/model_outputs.cpp [hunk 2]
```diff
@@ -216,6 +216,13 @@ void ModelOutputsPage::build(FormWindow * window, int8_t focusChannel)
   grid.spacer(PAGE_PADDING);
   grid.setLabelWidth(66);
 
+  new TextButton(window, grid.getLineSlot(), STR_ADD_ALL_TRIMS_TO_SUBTRIMS,
```
Comment (pfeerick) [inline radio/src/gui/colorlcd/model_outputs.cpp:219]: Wouldn't this actually be Move? It moves the trims to the offsets, aka subtrim, thus resetting the trims. I know where the confusion comes from, so lets not dwell on that ;)

Looks like a screen refresh is needed after this happens as well.

**Review by pfeerick — CHANGES_REQUESTED** [review]
Just some minor stuff - translation string / name, and a screen invalidation needed.

File: radio/src/gui/colorlcd/model_outputs.cpp (hunk 2 above)
Comment (kevinkoenig) [reply radio/src/gui/colorlcd/model_outputs.cpp:219]: > Wouldn't this actually be Move? It moves the trims to the offsets, aka subtrim, thus resetting the trims. I know where the confusion comes from, so lets not dwell on that ;)
> 
> Looks like a screen refresh is needed after this happens as well.

i have done the screen reset, and I am testing on simulator26.  I think it is actually Add and not Move.  If you move the trims, press the button, and then move the trims again, the numbers keep going up.  So it is Adding not Moving.

Let me know?

Comment (kevinkoenig) [reply radio/src/gui/colorlcd/model_outputs.cpp]: I made the change to the button so it says move, but I think it should be changed back to add.  If you like it this way then merge, otherwise I will change it back to Add

**Review by pfeerick — APPROVED** [review]
After some DM discussion, Add won ;)

**Comment by eshifri** [comment]
Wouldn't it be better to have this button in the header ("OUTPUTS")?
Or it is a part of the coming UI rework?

**Comment by pfeerick** [comment]
IMO, no, as the header in this instance (the overview screen) should be non-interactive... only any real-time output values. i.e. the output value for highlighted channel should be in the header, which is still to come ;)
